# Generated by Django 2.1.9 on 2019-07-11 13:42

from django.db import migrations, models
import voucher.utils


class Migration(migrations.Migration):

    dependencies = [("voucher", "0002_product_and_enrollment_keys")]

    operations = [
        migrations.AlterField(
            model_name="voucher",
            name="pdf",
            field=models.FileField(
                null=True, upload_to=voucher.utils.voucher_upload_path
            ),
        )
    ]
