# Generated by Django 2.1.7 on 2019-04-22 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("users", "0001_add_user")]

    operations = [
        migrations.CreateModel(
            name="LegalAddress",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(blank=True, max_length=60)),
                ("last_name", models.CharField(blank=True, max_length=60)),
                ("street_address_1", models.CharField(blank=True, max_length=60)),
                ("street_address_2", models.CharField(blank=True, max_length=60)),
                ("street_address_3", models.CharField(blank=True, max_length=60)),
                ("street_address_4", models.CharField(blank=True, max_length=60)),
                ("street_address_5", models.CharField(blank=True, max_length=60)),
                ("city", models.CharField(blank=True, max_length=50)),
                ("country", models.CharField(blank=True, max_length=2)),
                ("state_or_territory", models.CharField(blank=True, max_length=6)),
                ("postal_code", models.CharField(blank=True, max_length=10)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False},
        )
    ]
