# Generated by Django 2.1.7 on 2019-05-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0005_profile")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=False, help_text="The user account is active"
            ),
        )
    ]
