# Generated by Django 2.1.7 on 2019-06-10 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [("users", "0007_validate_country_and_state")]

    operations = [
        migrations.CreateModel(
            name="ChangeEmailRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("new_email", models.EmailField(max_length=254)),
                (
                    "code",
                    models.CharField(
                        default=users.models.generate_change_email_code,
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("confirmed", models.BooleanField(default=False)),
                (
                    "expires_on",
                    models.DateTimeField(
                        default=users.models.generate_change_email_expires
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_email_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterIndexTogether(
            name="changeemailrequest",
            index_together={("expires_on", "confirmed", "code")},
        ),
    ]
