# Generated by Django 2.2.3 on 2019-08-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("users", "0008_profile_fields_optional")]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="highest_education",
            field=models.CharField(
                blank=True,
                choices=[
                    (None, "----"),
                    ("Doctorate", "Doctorate"),
                    (
                        "Master's or professional degree",
                        "Master's or professional degree",
                    ),
                    ("Bachelor's degree", "Bachelor's degree"),
                    ("Associate degree", "Associate degree"),
                    ("Secondary/high school", "Secondary/high school"),
                    (
                        "Junior secondary/junior high/middle school",
                        "Junior secondary/junior high/middle school",
                    ),
                    ("Elementary/primary school", "Elementary/primary school"),
                    ("No formal education", "No formal education"),
                    ("Other education", "Other education"),
                ],
                default="",
                max_length=60,
            ),
        )
    ]
