# Generated by Django 2.2.4 on 2019-09-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("users", "0010_remove_username_ulid_default")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=50, unique=True),
        )
    ]
