# Generated by Django 2.2.20 on 2021-06-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("users", "0012_changeemailrequest")]

    operations = [
        migrations.CreateModel(
            name="BlockList",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("hashed_email", models.CharField(max_length=128)),
            ],
            options={"abstract": False},
        )
    ]
