# Generated by Django 3.2.17 on 2023-02-16 18:35

from django.db import migrations, models
from django.db.models.functions import Length


def truncate_long_user_names(apps, schema):
    """Truncate any User.name values > 255 characters"""
    User = apps.get_model("users", "User")
    for user in User.objects.annotate(namelen=Length("name")).filter(namelen__gt=255):
        user.name = user.name[:255]
        user.save()


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_blocklist"),
    ]

    operations = [
        migrations.RunPython(
            truncate_long_user_names, reverse_code=migrations.RunPython
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
