# Generated by Django 3.2.21 on 2023-09-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_alter_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="vat_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
