# Generated by Django 3.2.23 on 2023-12-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_alter_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="legaladdress",
            name="vat_id",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
