# Generated by Django 3.2.23 on 2023-12-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='legaladdress',
            name='vat_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='vat_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
