# Generated by Django 3.2.23 on 2024-01-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0015_legaladdress_vat_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="legaladdress",
            name="vat_id",
            field=models.CharField(blank=True, default="", max_length=30),
            preserve_default=False,
        ),
    ]
