# Generated by Django 4.2.30 on 2026-04-10 10:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_remove_null_vat_id"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="changeemailrequest",
            new_name="users_chang_expires_dbd4e5_idx",
            old_fields=("expires_on", "confirmed", "code"),
        ),
    ]
