# Generated by Django 5.2.17 on 2026-08-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compliance", "0001_add_export_inquiry_log"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportsinquirylog",
            name="reason_code",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
