options:
  merge-default-rules: false
files:
  include: 'static/scss/**/*.scss'
rules:
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2
  mixins-before-declarations: 2
  no-warn: 1
  no-duplicate-properties: 2
  no-debug: 1
  no-important: 0
  no-empty-rulesets: 2
  no-misspelled-properties: 2
  no-mergeable-selectors: 2
  no-trailing-whitespace: 2
  trailing-semicolon: 2
  declarations-before-nesting: 2
  space-between-parens: 2
  no-vendor-prefixes: 2
  one-declaration-per-line: 2
  space-before-colon: 2
  space-after-colon: 2
  space-before-bang: 2
  hex-notation:
    - 2
    -
      style: lowercase
  indentation:
    - 2
    -
      size: 2
  brace-style:
    - 2
    -
      allow-single-line: false
  empty-line-between-blocks: 2
  space-before-brace: 2
