FROM node:12.16.1
LABEL maintainer "ODL DevOps <mitx-devops@mit.edu>"

RUN apt-get update && apt-get install libelf1

COPY package.json scripts/ /tmp/

RUN YARN_VERSION=$(node /tmp/scripts/yarn_version.js) ; yarn policies set-version $YARN_VERSION

RUN mkdir -p /home/node/.cache/yarn

RUN chown node:node /home/node/.cache/yarn

USER node

WORKDIR /src/
