# Generated by Django 2.1.7 on 2019-04-18 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0001_squashed_0021"),
        ("cms", "0002_add_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursepage",
            name="background_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Background image size must be at least 1920x1080 pixels.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.Image",
            ),
        ),
        migrations.AddField(
            model_name="coursepage",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="URL to the video to be displayed for this course",
                null=True,
            ),
        ),
    ]
