# Generated by Django 2.1.7 on 2019-04-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cms", "0005_move_fields_to_product")]

    operations = [
        migrations.AlterField(
            model_name="coursepage",
            name="subhead",
            field=models.CharField(
                default="",
                help_text="A short subheading to appear below the title on the program/course page",
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="programpage",
            name="subhead",
            field=models.CharField(
                default="",
                help_text="A short subheading to appear below the title on the program/course page",
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
