# Generated by Django 2.1.7 on 2019-04-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cms", "0006_make_subhead_required")]

    operations = [
        migrations.AddField(
            model_name="coursepage",
            name="time_commitment",
            field=models.CharField(
                blank=True,
                help_text="A short description indicating about the time commitments.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="programpage",
            name="time_commitment",
            field=models.CharField(
                blank=True,
                help_text="A short description indicating about the time commitments.",
                max_length=100,
                null=True,
            ),
        ),
    ]
