# Generated by Django 2.1.7 on 2019-04-30 09:36

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0041_group_collection_permissions_verbose_name_plural"),
        ("cms", "0007_add_time_commitment"),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningOutcomesPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "heading",
                    models.CharField(
                        help_text="Heading highlighting the learning outcomes generally.",
                        max_length=250,
                    ),
                ),
                (
                    "sub_heading",
                    models.CharField(
                        help_text="Sub heading for learning outcomes.",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "outcome_items",
                    wagtail.core.fields.StreamField(
                        [("outcome", wagtail.core.blocks.TextBlock(icon="plus"))],
                        help_text="Detail about What you'll learn as learning outcome.",
                    ),
                ),
            ],
            options={"abstract": False},
            bases=("wagtailcore.page",),
        )
    ]
