# Generated by Django 2.1.7 on 2019-05-03 12:41

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0041_group_collection_permissions_verbose_name_plural"),
        ("cms", "0008_learningoutcomespage"),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningTechniquesPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "technique_items",
                    wagtail.core.fields.StreamField(
                        [
                            (
                                "techniques",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "heading",
                                            wagtail.core.blocks.CharBlock(
                                                max_length=100
                                            ),
                                        ),
                                        (
                                            "sub_heading",
                                            wagtail.core.blocks.CharBlock(
                                                max_length=250
                                            ),
                                        ),
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(),
                                        ),
                                    ]
                                ),
                            )
                        ],
                        help_text="Enter detail about how you'll learn.",
                    ),
                ),
            ],
            options={"abstract": False},
            bases=("wagtailcore.page",),
        )
    ]
