# Generated by Django 2.1.7 on 2019-05-02 14:01

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0041_group_collection_permissions_verbose_name_plural"),
        ("wagtailimages", "0001_squashed_0021"),
        ("cms", "0010_add_faqspage"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForTeamsPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "content",
                    wagtail.core.fields.RichTextField(
                        help_text="The content shown in the section"
                    ),
                ),
                (
                    "action_title",
                    models.CharField(
                        help_text="The text to show on the call to action button",
                        max_length=255,
                    ),
                ),
                (
                    "switch_layout",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="When checked, switches the position of the image and content, i.e. image on left and content on right.",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image size must be at least 750x505 pixels.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.Image",
                    ),
                ),
            ],
            options={"abstract": False},
            bases=("wagtailcore.page",),
        )
    ]
