# Generated by Django 2.1.7 on 2019-05-07 08:47

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('cms', '0010_add_faqspage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsOfServicesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('term_of_service', wagtail.core.fields.StreamField([('tos', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(max_length=100)), ('detail', wagtail.core.blocks.RichTextBlock())]))], help_text='Enter detail of term of service.')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
