# Generated by Django 2.1.7 on 2019-05-06 20:40

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0041_group_collection_permissions_verbose_name_plural"),
        ("wagtailimages", "0001_squashed_0021"),
        ("cms", "0011_for_teams_subpage"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhoShouldEnrollPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "content",
                    wagtail.core.fields.StreamField(
                        [
                            (
                                "item",
                                wagtail.core.blocks.RichTextBlock(
                                    features=["bold", "italic", "ol", "ul"], icon="plus"
                                ),
                            )
                        ],
                        help_text='Contents of the "Who Should Enroll" section.',
                    ),
                ),
                (
                    "switch_layout",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="Switch image to the left and content to the right",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image size must be at least 870x500 pixels.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.Image",
                    ),
                ),
            ],
            options={"abstract": False},
            bases=("wagtailcore.page",),
        )
    ]
