# Generated by Django 2.1.7 on 2019-05-07 12:13

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0041_group_collection_permissions_verbose_name_plural"),
        ("cms", "0012_who_should_enroll_subpage"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoursesInProgramPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "heading",
                    models.CharField(
                        help_text="The heading to show in this section", max_length=255
                    ),
                ),
                (
                    "body",
                    wagtail.core.fields.RichTextField(
                        help_text="The content to show above course carousel"
                    ),
                ),
            ],
            options={"abstract": False},
            bases=("wagtailcore.page",),
        )
    ]
