# Generated by Django 2.1.7 on 2019-05-08 20:08

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0041_group_collection_permissions_verbose_name_plural"),
        ("cms", "0014_resourcepage"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTestimonialsPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "heading",
                    models.CharField(
                        help_text="The heading to display on this section.",
                        max_length=255,
                    ),
                ),
                (
                    "subhead",
                    models.CharField(
                        help_text="Subhead to display below the heading.",
                        max_length=255,
                    ),
                ),
                (
                    "items",
                    wagtail.fields.StreamField(
                        [
                            (
                                "testimonial",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "name",
                                            wagtail.blocks.CharBlock(
                                                help_text="Name of the attestant.",
                                                max_length=100,
                                            ),
                                        ),
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(
                                                help_text="The title to display after the name.",
                                                max_length=255,
                                            ),
                                        ),
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                blank=True,
                                                help_text="The image to display on the testimonial",
                                                null=True,
                                            ),
                                        ),
                                        (
                                            "quote",
                                            wagtail.blocks.TextBlock(
                                                help_text="The quote that appears on the testimonial."
                                            ),
                                        ),
                                    ]
                                ),
                            )
                        ],
                        help_text="Add testimonials to display in this section.",
                    ),
                ),
            ],
            options={"verbose_name": "Testimonials Page"},
            bases=("wagtailcore.page",),
        )
    ]
