# Generated by Django 2.1.7 on 2019-05-14 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('cms', '0016_faculty_members_subpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('notification', models.CharField(help_text='Message that will be shown as notification.', max_length=250, unique=True)),
                ('is_enabled', models.BooleanField(blank=True, default=False, help_text='It will determine if notification is enabled/disabled.')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
