# Generated by Django 2.1.7 on 2019-05-20 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("cms", "0016_faculty_members_subpage")]

    operations = [
        migrations.AlterModelOptions(
            name="forteamspage", options={"verbose_name": "Text-Image Section"}
        ),
        migrations.AlterModelOptions(
            name="learningtechniquespage", options={"verbose_name": "Icon Grid"}
        ),
        migrations.AlterModelOptions(
            name="usertestimonialspage",
            options={"verbose_name": "Testimonials Section"},
        ),
    ]
