# Generated by Django 2.1.7 on 2019-05-22 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cms", "0020_section_fixes")]

    operations = [
        migrations.AddField(
            model_name="forteamspage",
            name="dark_theme",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="When checked, switches to dark theme (light text on dark background).",
            ),
        )
    ]
