# Generated by Django 2.1.7 on 2019-05-24 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0001_squashed_0021"),
        ("cms", "0021_text_image_dark_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursepage",
            name="background_video_url",
            field=models.URLField(
                blank=True,
                help_text="Background video that should play over the hero section. Must be an HLS video URL. Will cover background image if selected.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="background_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Background image size must be at least 1900x650 pixels.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.Image",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="background_video_url",
            field=models.URLField(
                blank=True,
                help_text="Background video that should play over the hero section. Must be an HLS video URL. Will cover background image if selected.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="subhead",
            field=models.CharField(
                default="",
                help_text="The subhead to display in the hero section on the home page.",
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="programpage",
            name="background_video_url",
            field=models.URLField(
                blank=True,
                help_text="Background video that should play over the hero section. Must be an HLS video URL. Will cover background image if selected.",
                null=True,
            ),
        ),
    ]
