# Generated by Django 2.1.7 on 2019-05-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cms", "0022_header_background_hls_video")]

    operations = [
        migrations.AddField(
            model_name="forteamspage",
            name="action_url",
            field=models.URLField(
                blank=True,
                help_text="The URL to go to when the action button is clicked.",
                null=True,
            ),
        )
    ]
