# Generated by Django 2.1.7 on 2019-05-23 08:02

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [("cms", "0023_text_image_section_action_url")]

    operations = [
        migrations.AddField(
            model_name="coursesinprogrampage",
            name="contents",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "item",
                        wagtail.core.blocks.PageChooserBlock(
                            required=False,
                            target_model=["cms.CoursePage", "cms.ProgramPage"],
                        ),
                    )
                ],
                blank=True,
                help_text="The courseware to display in this carousel",
            ),
        ),
        migrations.AddField(
            model_name="coursesinprogrampage",
            name="override_contents",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Manually select contents below. Otherwise displays all courses associated with the program.",
            ),
        ),
    ]
