# Generated by Django 2.1.7 on 2019-05-30 09:52

from django.db import migrations
from wagtail.core.models import Page


def get_home_page(apps):
    """
    Importing the Site model from the registry means if we access the root page from this
    model we will get an instance of the Page with only the basic model methods so we simply extract
    the ID of the page and hand it to the Page model imported directly.
    """
    Site = apps.get_model("wagtailcore", "Site")
    site = Site.objects.filter(is_default_site=True).first()
    if not site:
        raise Exception(
            "A default site is not set up. Please setup a default site before running this migration"
        )
    if not site.root_page:
        raise Exception(
            "No root (home) page set up. Please setup a root (home) page for the default site before running this migration"
        )
    return Page.objects.get(id=site.root_page.id)


def remove_catalog_page(apps, schema_editor):
    """
    Remove the catalog page
    """
    ContentType = apps.get_model("contenttypes.ContentType")
    catalog_content_type, _ = ContentType.objects.get_or_create(
        app_label="cms", model="catalogpage"
    )
    catalog = Page.objects.get(content_type_id=catalog_content_type.id)
    if catalog:
        catalog.delete()


def create_catalog_page(apps, schema_editor):
    """
    Create a catalog page under the home page
    """
    ContentType = apps.get_model("contenttypes.ContentType")
    CatalogPage = apps.get_model("cms", "CatalogPage")
    catalog_content_type, _ = ContentType.objects.get_or_create(
        app_label="cms", model="catalogpage"
    )
    home_page = get_home_page(apps)

    catalog = CatalogPage.objects.first()

    if not catalog:
        catalog = Page(
            title="Courseware Catalog",
            content_type_id=catalog_content_type.id,
            slug="catalog",
        )
        catalog = home_page.add_child(instance=catalog)
        catalog.save_revision().publish()


class Migration(migrations.Migration):

    dependencies = [("cms", "0030_catalog_page_model")]

    operations = [migrations.RunPython(create_catalog_page, remove_catalog_page)]
