# Generated by Django 2.1.7 on 2019-06-10 11:25

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0041_group_collection_permissions_verbose_name_plural"),
        ("cms", "0032_product_video_hls"),
    ]

    operations = [
        migrations.CreateModel(
            name="TextSection",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "content",
                    wagtail.core.fields.RichTextField(
                        help_text="The content shown in the section"
                    ),
                ),
                (
                    "action_title",
                    models.CharField(
                        blank=True,
                        help_text="The text to show on the call to action button. Note: action button is visible only when both url and title are configured.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "action_url",
                    models.URLField(
                        blank=True,
                        help_text="The URL to go to when the action button is clicked. Note: action button is visible only when both url and title are configured.",
                        null=True,
                    ),
                ),
                (
                    "dark_theme",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="When checked, switches to dark theme (light text on dark background).",
                    ),
                ),
            ],
            options={"abstract": False},
            bases=("wagtailcore.page",),
        )
    ]
