# Generated by Django 2.1.7 on 2019-06-17 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("cms", "0033_text_section_page")]

    operations = [
        migrations.AlterField(
            model_name="coursepage",
            name="thumbnail_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Thumbnail size must be at least 550x310 pixels.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.Image",
            ),
        ),
        migrations.AlterField(
            model_name="programpage",
            name="thumbnail_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Thumbnail size must be at least 550x310 pixels.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.Image",
            ),
        ),
    ]
