# Generated by Django 2.1.9 on 2019-06-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cms", "0034_alter_helpttext_thumbnail")]

    operations = [
        migrations.AlterField(
            model_name="coursepage",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="URL to the video to be displayed for this program/course. It can be an HLS or Youtube video URL.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="programpage",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="URL to the video to be displayed for this program/course. It can be an HLS or Youtube video URL.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="textvideosection",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="The URL of the video to display. It can be an HLS or Youtube video URL.",
                null=True,
            ),
        ),
    ]
