# Generated by Django 2.1.9 on 2019-07-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cms", "0035_alter_helptext_video_url")]

    operations = [
        migrations.AlterField(
            model_name="facultymemberspage",
            name="subhead",
            field=models.CharField(
                blank=True,
                help_text="The subhead to display for this section on the product page.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="learningoutcomespage",
            name="sub_heading",
            field=models.CharField(
                blank=True,
                help_text="Sub heading for learning outcomes.",
                max_length=250,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="resourcepage",
            name="sub_heading",
            field=models.CharField(
                blank=True,
                help_text="Sub heading of the resource page.",
                max_length=250,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="usertestimonialspage",
            name="subhead",
            field=models.CharField(
                blank=True,
                help_text="Subhead to display below the heading.",
                max_length=255,
                null=True,
            ),
        ),
    ]
