# Generated by Django 2.1.9 on 2019-07-03 09:59
import wagtail.core.fields
from bs4 import BeautifulSoup
from django.db import migrations


def html_to_plain_text(html_str):
    """
    Takes an HTML string and returns text with HTML tags removed and line breaks replaced with spaces.
    Shamelessly copied from open-discussions.

    Args:
        html_str (str): A string containing HTML tags
    Returns:
        str: Plain text
    """
    soup = BeautifulSoup(html_str, features="html.parser")
    return soup.get_text().replace("\n", " ")


def convert_to_plaintext(apps, schema_editor):
    """
    Because going back from RichText to CharField we don't want any HTML to be embedded within
    the field content so the content will be extracted and any html stripped away.
    """
    if not schema_editor.connection.alias == "default":
        return
    LearningOutcomesPage = apps.get_model("cms", "LearningOutcomesPage")
    for page in LearningOutcomesPage.objects.all():
        page.sub_heading = html_to_plain_text(page.sub_heading)
        page.save()


class Migration(migrations.Migration):

    dependencies = [("cms", "0037_featured_product")]

    operations = [
        migrations.RunPython(migrations.RunPython.noop, convert_to_plaintext),
        migrations.AlterField(
            model_name="learningoutcomespage",
            name="sub_heading",
            field=wagtail.core.fields.RichTextField(
                help_text="Sub heading for learning outcomes.", blank=True, null=True
            ),
        ),
    ]
