# Generated by Django 2.1.9 on 2019-07-03 11:43

from django.db import migrations, models
import wagtail.core.fields


def copy_description_to_catalog_details(apps, schema_editor):
    """
    Copy the existing page description to the new `catalog_details`
    field.
    """
    CoursePage = apps.get_model("cms", "CoursePage")
    ProgramPage = apps.get_model("cms", "ProgramPage")

    CoursePage.objects.update(catalog_details=models.F("description"))
    ProgramPage.objects.update(catalog_details=models.F("description"))


def dummy_reverse(apps, schema_editor):
    """
    Dummy reverse placeholder for Django to be able to reverse this
    migration.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [("cms", "0038_learning_outcomes_subhead_richtext")]

    operations = [
        migrations.AddField(
            model_name="coursepage",
            name="catalog_details",
            field=wagtail.core.fields.RichTextField(
                blank=True,
                help_text="The description shown on the catalog page for this product",
            ),
        ),
        migrations.AddField(
            model_name="programpage",
            name="catalog_details",
            field=wagtail.core.fields.RichTextField(
                blank=True,
                help_text="The description shown on the catalog page for this product",
            ),
        ),
        migrations.AlterField(
            model_name="coursepage",
            name="description",
            field=wagtail.core.fields.RichTextField(
                blank=True, help_text="The description shown on the product page"
            ),
        ),
        migrations.AlterField(
            model_name="programpage",
            name="description",
            field=wagtail.core.fields.RichTextField(
                blank=True, help_text="The description shown on the product page"
            ),
        ),
        migrations.RunPython(copy_description_to_catalog_details, dummy_reverse),
    ]
