# Generated by Django 2.2.3 on 2019-07-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cms", "0039_product_page_catalog_details")]

    operations = [
        migrations.AddField(
            model_name="whoshouldenrollpage",
            name="heading",
            field=models.CharField(
                default="Who Should Enroll",
                help_text="The heading to show in this section",
                max_length=255,
            ),
        )
    ]
