# Generated by Django 2.2.4 on 2019-09-18 07:20

from django.db import migrations
from wagtail.core.models import Page

from cms.constants import CERTIFICATE_INDEX_SLUG


def get_home_page(apps):
    """
    Importing the Site model from the registry means if we access the root page from this
    model we will get an instance of the Page with only the basic model methods so we simply extract
    the ID of the page and hand it to the Page model imported directly.
    """
    Site = apps.get_model("wagtailcore", "Site")
    site = Site.objects.filter(is_default_site=True).first()
    if not site:
        raise Exception(
            "A default site is not set up. Please setup a default site before running this migration"
        )
    if not site.root_page:
        raise Exception(
            "No root (home) page set up. Please setup a root (home) page for the default site before running this migration"
        )
    return Page.objects.get(id=site.root_page.id)


def remove_index_page(apps, schema_editor):
    """
    Remove the certificate index page
    """
    ContentType = apps.get_model("contenttypes.ContentType")
    index_content_type, _ = ContentType.objects.get_or_create(
        app_label="cms", model="certificateindexpage"
    )
    index_page = Page.objects.get(content_type_id=index_content_type.id)
    if index_page:
        index_page.delete()


def create_index_page(apps, schema_editor):
    """
    Create a certificate index page under the home page
    """
    ContentType = apps.get_model("contenttypes.ContentType")
    CertificateIndexPage = apps.get_model("cms", "CertificateIndexPage")
    index_content_type, _ = ContentType.objects.get_or_create(
        app_label="cms", model="certificateindexpage"
    )
    home_page = get_home_page(apps)

    index_page = CertificateIndexPage.objects.first()

    if not index_page:
        index_page = Page(
            title="Certificate Index Page",
            content_type_id=index_content_type.id,
            slug=CERTIFICATE_INDEX_SLUG,
        )
        index_page = home_page.add_child(instance=index_page)
        index_page.save_revision().publish()


class Migration(migrations.Migration):

    dependencies = [("cms", "0042_certificate_index_page")]

    operations = [migrations.RunPython(create_index_page, remove_index_page)]
