# Generated by Django 2.2.8 on 2020-01-31 14:31

import cms.blocks
from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [("cms", "0044_external_course_cms_page")]

    operations = [
        migrations.AddField(
            model_name="certificatepage",
            name="overrides",
            field=wagtail.fields.StreamField(
                [
                    (
                        "course_run",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "readable_id",
                                    cms.blocks.CourseRunFieldBlock(
                                        help_text="Course run to add the override for"
                                    ),
                                ),
                                (
                                    "CEUs",
                                    wagtail.blocks.DecimalBlock(
                                        help_text="CEUs to override for this CourseRun, for display on the certificate"
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                help_text="Overrides for specific runs of this Course/Program",
                validators=[cms.blocks.validate_unique_readable_ids],
            ),
        )
    ]
