# Generated by Django 2.2.13 on 2021-01-11 12:37

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [("cms", "0047_externalprogrampage")]

    operations = [
        migrations.AlterField(
            model_name="coursesinprogrampage",
            name="contents",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "item",
                        wagtail.core.blocks.PageChooserBlock(
                            page_type=[
                                "cms.CoursePage",
                                "cms.ProgramPage",
                                "cms.ExternalCoursePage",
                            ],
                            required=False,
                        ),
                    )
                ],
                blank=True,
                help_text="The courseware to display in this carousel",
            ),
        )
    ]
