# Generated by Django 2.2.13 on 2021-02-09 12:51

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0045_assign_unlock_grouppagepermission"),
        ("cms", "0049_positive_fields_constraints"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsAndEventsPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "heading",
                    models.CharField(
                        help_text="The heading to display on this section.",
                        max_length=255,
                    ),
                ),
                (
                    "items",
                    wagtail.core.fields.StreamField(
                        [
                            (
                                "news_and_events",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "content_type",
                                            wagtail.core.blocks.CharBlock(
                                                help_text="Specify the news/events type here.",
                                                max_length=100,
                                            ),
                                        ),
                                        (
                                            "title",
                                            wagtail.core.blocks.CharBlock(
                                                help_text="Specify the news/events title here.",
                                                max_length=255,
                                            ),
                                        ),
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                blank=True,
                                                help_text="Specify the image for news/events section.",
                                                null=True,
                                            ),
                                        ),
                                        (
                                            "content",
                                            wagtail.core.blocks.TextBlock(
                                                help_text="Specify the news/events content here."
                                            ),
                                        ),
                                        (
                                            "call_to_action",
                                            wagtail.core.blocks.CharBlock(
                                                help_text="Specify the news/events call-to-action text here (e.g: 'Read More').",
                                                max_length=100,
                                            ),
                                        ),
                                        (
                                            "action_url",
                                            wagtail.core.blocks.URLBlock(
                                                help_text="Specify the news/events action-url here (like a link to an article e.g: https://www.google.com/search?q=article)."
                                            ),
                                        ),
                                    ]
                                ),
                            )
                        ],
                        help_text="Add news and events updates to display in this section.",
                    ),
                ),
            ],
            options={"verbose_name": "News and Events"},
            bases=("wagtailcore.page",),
        )
    ]
