# Generated by Django 2.2.20 on 2021-04-28 16:28

"""
Data migrations moved to cms/migrations/0052_new_page_data_migrations.py in response to Page model change
"""

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0059_apply_collection_ordering"),
        ("cms", "0050_news_and_events_page"),
    ]

    operations = [
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop)
    ]
