# Generated by Django 2.2.20 on 2021-04-28 16:28

"""
Data migrations is discontinued as all the index pages are created on RC and Prod.
Also, we have a management command `configure_wagtail` to handle the index page creation
new instances.

Reason for discontinuation: It adds extra work whenever we upgrade Wagtail, and we don't really need it now.
"""

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0062_comment_models_and_pagesubscription"),
        ("cms", "0051_new_page_data_migrations"),
    ]
    operations = [
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop)
    ]
