# Generated by Django 3.2.14 on 2022-08-15 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('cms', '0052_new_page_data_migrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatepage',
            name='partner_logo',
            field=models.ForeignKey(blank=True, help_text='Optional Partner logo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
