# Generated by Django 3.2.14 on 2022-08-23 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0023_add_choose_permissions"),
        ("cms", "0052_new_page_data_migrations"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificatepage",
            name="institute_text",
            field=models.CharField(
                blank=True,
                help_text="Specify the institute text",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="certificatepage",
            name="partner_logo",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional Partner logo size must be at least 600x200 pixel",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="certificatepage",
            name="partner_logo_placement",
            field=models.IntegerField(
                blank=True,
                choices=[(None, "No display"), (1, "First"), (2, "Second")],
                default=2,
                help_text="Partner logo placement on certificate, logo size must be at least 600x200 pixel",
                null=True,
            ),
        ),
    ]
