# Generated by Django 3.2.18 on 2023-03-24 11:37

from django.db import migrations
from cms.models import CoursePage, ExternalCoursePage


def migrate_associate_existing_topics(apps, app_schema):
    """Pre-populate the existing course pages with the topics from their associated courses"""
    all_course_pages = list(CoursePage.objects.all()) + list(
        ExternalCoursePage.objects.all()
    )
    for course_page in all_course_pages:
        course_page.topics.set(course_page.course.topics.all())
        course_page.save()


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0055_associate_courseware_page_with_topics"),
    ]

    operations = [
        migrations.RunPython(
            migrate_associate_existing_topics, migrations.RunPython.noop
        )
    ]
