# Generated by Django 3.2.18 on 2023-04-14 00:32

from django.db import migrations, models
import django.db.models.deletion
import wagtailmetadata.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('cms', '0056_prepopulate_coursepage_topics'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebinarIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='WebinarPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('register_url', models.URLField(blank=True, help_text='Registration URL', null=True)),
                ('recording_url', models.URLField(blank=True, help_text='Recording URL', null=True)),
                ('start_datetime', models.DateTimeField(blank=True, help_text='The start date and time of the webinar.', null=True)),
                ('duration', models.PositiveIntegerField(blank=True, help_text='The duration of the webinar.', null=True)),
                ('category', models.CharField(choices=[('upcoming', 'Upcoming'), ('ondemand', 'On-Demand')], max_length=20)),
                ('search_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Search image')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtailmetadata.models.MetadataMixin, 'wagtailcore.page', models.Model),
        ),
    ]
