# Generated by Django 3.2.18 on 2023-04-14 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0023_add_choose_permissions"),
        ("cms", "0057_webinarindexpage_webinarpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="webinarpage",
            name="banner_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Image for the Webinar.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
