# Generated by Django 3.2.18 on 2023-04-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0058_webinarpage_banner_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webinarpage',
            name='recording_url',
        ),
        migrations.RemoveField(
            model_name='webinarpage',
            name='register_url',
        ),
        migrations.AddField(
            model_name='webinarpage',
            name='action_title',
            field=models.CharField(blank=True, help_text='The text to show on the call to action button i.e. REGISTER, VIEW RECORDING', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='webinarpage',
            name='action_url',
            field=models.URLField(blank=True, help_text='The URL to go to when the action button is clicked.', null=True),
        ),
    ]
