# Generated by Django 3.2.18 on 2023-08-04 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0033_remove_course_coursetopic_association'),
        ('cms', '0060_webinarindexpage_webinarpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webinarpage',
            name='action_title',
        ),
        migrations.AddField(
            model_name='webinarpage',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='courses.course'),
        ),
        migrations.AddField(
            model_name='webinarpage',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='courses.program'),
        ),
        migrations.AddField(
            model_name='webinarpage',
            name='sub_heading',
            field=models.CharField(blank=True, help_text='Sub heading of the webinar page.', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='webinarpage',
            name='action_url',
            field=models.URLField(blank=True, help_text='Specify the webinar action-url here (like a link to an external webinar page).', null=True),
        ),
    ]
