# Generated by Django 3.2.20 on 2023-08-18 06:47

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0061_added_new_webinar_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="webinarpage",
            name="body_text",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Longer description text of the webinar.",
                null=True,
            ),
        ),
    ]
