# Generated by Django 3.2.20 on 2023-08-24 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0023_add_choose_permissions"),
        ("cms", "0062_webinarpage_body_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="webinarindexpage",
            name="banner_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Banner image for the Webinar list page.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
