# Generated by Django 3.2.23 on 2023-11-16 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0023_add_choose_permissions"),
        ("wagtailcore", "0062_comment_models_and_pagesubscription"),
        ("cms", "0064_productpage_format_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "sub_heading",
                    models.CharField(
                        blank=True,
                        default="Online learning stories for professionals, from MIT",
                        help_text="Sub heading of the blog page.",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "recent_posts_heading",
                    models.CharField(
                        blank=True,
                        default="Top Most Recent Posts",
                        help_text="Heading of the recent posts section.",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "more_posts_heading",
                    models.CharField(
                        blank=True,
                        default="More From MIT",
                        help_text="Heading of the more posts section.",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "banner_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Banner image for the Blog page.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
    ]
