# Generated by Django 3.2.23 on 2024-01-02 20:05

from django.db import migrations


def migrate_content_type_id(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    BlogIndexPage = apps.get_model("cms", "BlogIndexPage")
    blog_index_content_type, _ = ContentType.objects.get_or_create(
        app_label="cms", model="blogindexpage"
    )
    blog_index = BlogIndexPage.objects.first()
    if blog_index:
        blog_page_revisions = Revision.objects.filter(object_id=blog_index.id)
        for revision in blog_page_revisions:
            blog_page_content = dict(revision.content)
            blog_page_content["content_type"] = blog_page_content["content_type_id"]
            revision.content = blog_page_content
            revision.save()

    WebinarIndexPage = apps.get_model("cms", "WebinarIndexPage")
    webinar_index_content_type, _ = ContentType.objects.get_or_create(
        app_label="cms", model="webinarindexpage"
    )
    webinar_index = WebinarIndexPage.objects.first()
    if webinar_index:
        webinar_page_revisions = Revision.objects.filter(object_id=webinar_index.id)
        for revision in webinar_page_revisions:
            webinar_page_content = dict(revision.content)
            webinar_page_content["content_type"] = webinar_page_content["content_type_id"]
            revision.content = webinar_page_content
            revision.save()


class Migration(migrations.Migration):
    dependencies = [
        ('cms', '0065_blogindexpage'),
        ('wagtailcore', '0071_populate_revision_content_type'),
    ]

    run_before = [("wagtailcore", "0072_alter_revision_content_type_notnull"), ]

    operations = [migrations.RunPython(migrate_content_type_id, migrations.RunPython.noop)]
