# Generated by Django 4.2.9 on 2024-03-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0068_enterprisepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursepage",
            name="marketing_hubspot_form_id",
            field=models.CharField(
                blank=True,
                help_text="The HubSpot form ID associated with the program/course page.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="externalcoursepage",
            name="marketing_hubspot_form_id",
            field=models.CharField(
                blank=True,
                help_text="The HubSpot form ID associated with the program/course page.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="externalprogrampage",
            name="marketing_hubspot_form_id",
            field=models.CharField(
                blank=True,
                help_text="The HubSpot form ID associated with the program/course page.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="programpage",
            name="marketing_hubspot_form_id",
            field=models.CharField(
                blank=True,
                help_text="The HubSpot form ID associated with the program/course page.",
                max_length=50,
            ),
        ),
    ]
