# Generated by Django 4.2.11 on 2024-07-08 07:15

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0039_add_external_course_id_and_course_run_id"),
        ("cms", "0069_signup_for_more_information"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursepage",
            name="topics",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True,
                help_text="The topics for this course page.",
                to="courses.coursetopic",
            ),
        ),
        migrations.AlterField(
            model_name="externalcoursepage",
            name="topics",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True,
                help_text="The topics for this course page.",
                to="courses.coursetopic",
            ),
        ),
    ]
