# Generated by Django 4.2.13 on 2024-07-25 11:29

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0070_alter_coursepage_topics_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificatepage",
            name="signatories",
            field=wagtail.fields.StreamField(
                [
                    (
                        "signatory",
                        wagtail.blocks.PageChooserBlock(
                            page_type=["cms.SignatoryPage"], required=False
                        ),
                    )
                ],
                blank=True,
                help_text="You can choose upto 5 signatories.",
                use_json_field=True,
            ),
        ),
    ]
