# Generated by Django 4.2.15 on 2024-08-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0071_alter_certificatepage_signatories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursepage",
            name="format",
            field=models.CharField(
                choices=[
                    ("Online", "Online"),
                    ("Hybrid", "Hybrid"),
                    ("Other", "Other"),
                ],
                default="Online",
                help_text="A short description indicating the format of a program or course",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="externalcoursepage",
            name="format",
            field=models.CharField(
                choices=[
                    ("Online", "Online"),
                    ("Hybrid", "Hybrid"),
                    ("Other", "Other"),
                ],
                default="Online",
                help_text="A short description indicating the format of a program or course",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="externalprogrampage",
            name="format",
            field=models.CharField(
                choices=[
                    ("Online", "Online"),
                    ("Hybrid", "Hybrid"),
                    ("Other", "Other"),
                ],
                default="Online",
                help_text="A short description indicating the format of a program or course",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="programpage",
            name="format",
            field=models.CharField(
                choices=[
                    ("Online", "Online"),
                    ("Hybrid", "Hybrid"),
                    ("Other", "Other"),
                ],
                default="Online",
                help_text="A short description indicating the format of a program or course",
                max_length=20,
            ),
        ),
    ]
