# Generated by Django 4.2.16 on 2024-12-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0072_add_hybrid_courseware_format_option"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursepage",
            name="max_weeks",
            field=models.SmallIntegerField(
                blank=True,
                help_text="The maximum number of weeks required to complete the course/program.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="coursepage",
            name="min_weeks",
            field=models.SmallIntegerField(
                blank=True,
                help_text="The minimum number of weeks required to complete the course/program.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="externalcoursepage",
            name="max_weeks",
            field=models.SmallIntegerField(
                blank=True,
                help_text="The maximum number of weeks required to complete the course/program.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="externalcoursepage",
            name="min_weeks",
            field=models.SmallIntegerField(
                blank=True,
                help_text="The minimum number of weeks required to complete the course/program.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="externalprogrampage",
            name="max_weeks",
            field=models.SmallIntegerField(
                blank=True,
                help_text="The maximum number of weeks required to complete the course/program.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="externalprogrampage",
            name="min_weeks",
            field=models.SmallIntegerField(
                blank=True,
                help_text="The minimum number of weeks required to complete the course/program.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="programpage",
            name="max_weeks",
            field=models.SmallIntegerField(
                blank=True,
                help_text="The maximum number of weeks required to complete the course/program.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="programpage",
            name="min_weeks",
            field=models.SmallIntegerField(
                blank=True,
                help_text="The minimum number of weeks required to complete the course/program.",
                null=True,
            ),
        ),
    ]
