# Generated by Django 4.2.16 on 2024-12-04 08:12

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models

import cms.models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0040_alter_courserun_courseware_id"),
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("cms", "0072_add_hybrid_courseware_format_option"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommonChildIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                cms.models.CanCreatePageMixin,
                cms.models.DisableSitemapURLMixin,
                "wagtailcore.page",
            ),
        ),
        migrations.CreateModel(
            name="LearningTechniquesCommonPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "technique_items",
                    wagtail.fields.StreamField(
                        [
                            (
                                "techniques",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "heading",
                                            wagtail.blocks.CharBlock(max_length=100),
                                        ),
                                        (
                                            "sub_heading",
                                            wagtail.blocks.CharBlock(max_length=250),
                                        ),
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(),
                                        ),
                                    ]
                                ),
                            )
                        ],
                        help_text="Enter detail about how you'll learn.",
                        use_json_field=True,
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="courses.platform",
                    ),
                ),
            ],
            options={
                "verbose_name": "Icon Grid - common",
            },
            bases=(cms.models.DisableSitemapURLMixin, "wagtailcore.page", models.Model),
        ),
        migrations.CreateModel(
            name="ForTeamsCommonPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "content",
                    wagtail.fields.RichTextField(
                        help_text="The content shown in the section"
                    ),
                ),
                (
                    "action_title",
                    models.CharField(
                        help_text="The text to show on the call to action button",
                        max_length=255,
                    ),
                ),
                (
                    "action_url",
                    models.URLField(
                        blank=True,
                        help_text="The URL to go to when the action button is clicked.",
                        null=True,
                    ),
                ),
                (
                    "dark_theme",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="When checked, switches to dark theme (light text on dark background).",
                    ),
                ),
                (
                    "switch_layout",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="When checked, switches the position of the image and content, i.e. image on left and content on right.",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image size must be at least 750x505 pixels.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="courses.platform",
                    ),
                ),
            ],
            options={
                "verbose_name": "Text-Image Section - common",
            },
            bases=(cms.models.DisableSitemapURLMixin, "wagtailcore.page", models.Model),
        ),
    ]
