# Generated by Django 4.2.16 on 2024-11-29 10:50

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models

import cms.models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("cms", "0072_add_hybrid_courseware_format_option"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseOverviewPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "heading",
                    models.CharField(
                        blank=True,
                        help_text="The Heading to show in this section.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "overview",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="A subheading to provide additional context or information.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Overview",
            },
            bases=(cms.models.DisableSitemapURLMixin, "wagtailcore.page"),
        ),
    ]
