# Generated by Django 4.2.16 on 2024-12-02 13:55

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0072_add_hybrid_courseware_format_option"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificatepage",
            name="CEUs",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Optional field for CEU (continuing education unit).",
                max_digits=5,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
    ]
