# Generated by Django 4.2.16 on 2024-12-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0073_course_overview_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursepage",
            name="max_weeks",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="The maximum number of weeks required to complete the course/program.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="coursepage",
            name="min_weeks",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="The minimum number of weeks required to complete the course/program.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="externalcoursepage",
            name="max_weeks",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="The maximum number of weeks required to complete the course/program.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="externalcoursepage",
            name="min_weeks",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="The minimum number of weeks required to complete the course/program.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="externalprogrampage",
            name="max_weeks",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="The maximum number of weeks required to complete the course/program.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="externalprogrampage",
            name="min_weeks",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="The minimum number of weeks required to complete the course/program.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="programpage",
            name="max_weeks",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="The maximum number of weeks required to complete the course/program.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="programpage",
            name="min_weeks",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="The minimum number of weeks required to complete the course/program.",
                null=True,
            ),
        ),
    ]
