# Generated by Django 4.2.16 on 2024-12-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0075_add_min_max_weeks"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursepage",
            name="max_weekly_hours",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="The maximum number of hours per week required to complete the course.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="coursepage",
            name="min_weekly_hours",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="The minimum number of hours per week required to complete the course.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="externalcoursepage",
            name="max_weekly_hours",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="The maximum number of hours per week required to complete the course.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="externalcoursepage",
            name="min_weekly_hours",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="The minimum number of hours per week required to complete the course.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="externalprogrampage",
            name="max_weekly_hours",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="The maximum number of hours per week required to complete the course.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="externalprogrampage",
            name="min_weekly_hours",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="The minimum number of hours per week required to complete the course.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="programpage",
            name="max_weekly_hours",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="The maximum number of hours per week required to complete the course.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="programpage",
            name="min_weekly_hours",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="The minimum number of hours per week required to complete the course.",
                null=True,
            ),
        ),
    ]
