# Generated by Django 4.2.17 on 2025-01-01 14:39

import django.db.models.deletion
from django.db import migrations, models


def populate_course_language(apps, schema_editor):
    """Prepopulate the course language for the course pages"""

    CoursePage = apps.get_model("cms.CoursePage")
    ExternalCoursePage = apps.get_model("cms.ExternalCoursePage")
    CourseLanguage = apps.get_model("courses.CourseLanguage")
    course_language_english = CourseLanguage.objects.get(name="English")

    CoursePage.objects.update(language=course_language_english)
    ExternalCoursePage.objects.update(language=course_language_english)


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0042_add_language"),
        ("cms", "0076_min_max_weekly_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursepage",
            name="language",
            field=models.ForeignKey(
                blank=True,
                help_text="The course language for this page",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="courses.courselanguage",
            ),
        ),
        migrations.AddField(
            model_name="externalcoursepage",
            name="language",
            field=models.ForeignKey(
                blank=True,
                help_text="The course language for this page",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="courses.courselanguage",
            ),
        ),
        migrations.RunPython(
            populate_course_language, reverse_code=migrations.RunPython.noop
        ),
    ]
