# Generated by Django 4.2.17 on 2025-01-01 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0077_add_course_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursepage",
            name="language",
            field=models.ForeignKey(
                default="",
                help_text="The course language for this page",
                on_delete=django.db.models.deletion.PROTECT,
                to="courses.courselanguage",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="externalcoursepage",
            name="language",
            field=models.ForeignKey(
                default="",
                help_text="The course language for this page",
                on_delete=django.db.models.deletion.PROTECT,
                to="courses.courselanguage",
            ),
            preserve_default=False,
        ),
    ]
