# Generated by Django 4.2.18 on 2025-02-25 19:52

import cms.blocks
from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0079_make_language_non_nullable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facultymemberspage",
            name="members",
            field=wagtail.fields.StreamField(
                [
                    (
                        "member",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "name",
                                    wagtail.blocks.CharBlock(
                                        help_text="Name of the faculty member.",
                                        max_length=100,
                                    ),
                                ),
                                (
                                    "image",
                                    cms.blocks.APIImageChooserBlock(
                                        help_text="Profile image size must be at least 300x300 pixels."
                                    ),
                                ),
                                (
                                    "description",
                                    wagtail.blocks.RichTextBlock(
                                        help_text="A brief description about the faculty member."
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                help_text="The faculty members to display on this page",
                use_json_field=True,
            ),
        ),
    ]
