# Generated by Django 4.2.23 on 2025-08-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0082_alter_certificatepage_display_mit_seal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursepage",
            name="format",
            field=models.CharField(
                choices=[("Online", "Online"), ("Hybrid", "Hybrid")],
                default="Online",
                help_text="A short description indicating the format of a program or course",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="externalcoursepage",
            name="format",
            field=models.CharField(
                choices=[("Online", "Online"), ("Hybrid", "Hybrid")],
                default="Online",
                help_text="A short description indicating the format of a program or course",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="externalprogrampage",
            name="format",
            field=models.CharField(
                choices=[("Online", "Online"), ("Hybrid", "Hybrid")],
                default="Online",
                help_text="A short description indicating the format of a program or course",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="programpage",
            name="format",
            field=models.CharField(
                choices=[("Online", "Online"), ("Hybrid", "Hybrid")],
                default="Online",
                help_text="A short description indicating the format of a program or course",
                max_length=20,
            ),
        ),
    ]
