# Generated by Django 2.1.7 on 2019-06-18 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0013_coupon_assignment_email_index"),
        ("hubspot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HubspotLineResync",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ecommerce.Line"
                    ),
                ),
            ],
        )
    ]
