# Generated by Django 2.2.4 on 2019-10-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleapiauth',
            name='id_token',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
