# Generated by Django 2.2.4 on 2019-10-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponGenerationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('transaction_id', models.CharField(db_index=True, max_length=100)),
                ('completed', models.BooleanField(default=False)),
                ('spreadsheet_updated', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
