# Generated by Django 2.2.4 on 2019-10-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0002_coupongenerationrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAccountCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('value', models.TextField(max_length=3000)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
