# Generated by Django 2.2.4 on 2019-11-04 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("sheets", "0002_nullable_google_api_auth_user")]

    operations = [
        migrations.RemoveField(
            model_name="coupongenerationrequest", name="spreadsheet_updated"
        )
    ]
