# Generated by Django 2.2.4 on 2019-11-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("sheets", "0004_rename_transaction_id")]

    operations = [
        migrations.CreateModel(
            name="GoogleFileWatch",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("file_id", models.CharField(db_index=True, max_length=100)),
                ("channel_id", models.CharField(db_index=True, max_length=50)),
                ("activation_date", models.DateTimeField()),
                ("expiration_date", models.DateTimeField(db_index=True, unique=True)),
                (
                    "version",
                    models.IntegerField(
                        blank=True, db_index=True, null=True, unique=True
                    ),
                ),
            ],
            options={"abstract": False},
        )
    ]
