# Generated by Django 2.2.4 on 2019-12-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("sheets", "0005_googlefilewatch")]

    operations = [
        migrations.AddField(
            model_name="coupongenerationrequest",
            name="date_completed",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="coupongenerationrequest",
            name="raw_data",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
