# Generated by Django 2.2.8 on 2020-01-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("sheets", "0008_remove_coupongenerationrequest_completed")]

    operations = [
        migrations.AddField(
            model_name="coupongenerationrequest",
            name="coupon_name",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="coupongenerationrequest",
            name="purchase_order_id",
            field=models.CharField(max_length=100),
        ),
    ]
