# Generated by Django 2.2.8 on 2020-01-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("sheets", "0010_fill_in_gen_request_coupon_name")]

    operations = [
        migrations.AlterField(
            model_name="coupongenerationrequest",
            name="coupon_name",
            field=models.CharField(db_index=True, max_length=256),
        )
    ]
