# Generated by Django 2.2.10 on 2020-03-03 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("sheets", "0013_deferralrequest")]

    operations = [
        migrations.AlterField(
            model_name="googlefilewatch",
            name="channel_id",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="googlefilewatch",
            name="version",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="googlefilewatch", unique_together={("file_id", "version")}
        ),
    ]
