# Generated by Django 2.2.10 on 2020-04-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("sheets", "0014_file_watch_for_assignment_sheets")]

    operations = [
        migrations.AddField(
            model_name="googlefilewatch",
            name="last_request_received",
            field=models.DateTimeField(blank=True, null=True),
        )
    ]
