# Generated by Django 2.2.10 on 2020-10-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("sheets", "0016_remove_file_watch_expiration_idx")]

    operations = [
        migrations.CreateModel(
            name="FileWatchRenewalAttempt",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sheet_type",
                    models.CharField(
                        choices=[
                            ("enrollrequest", "enrollrequest"),
                            ("enrollassign", "enrollassign"),
                            ("enrollchange", "enrollchange"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("sheet_file_id", models.CharField(db_index=True, max_length=100)),
                ("date_attempted", models.DateTimeField(auto_now_add=True)),
                ("result", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "result_status_code",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
            ],
        )
    ]
