# Generated by Django 2.1.7 on 2019-03-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("ecommerce", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="coupon", name="enabled", field=models.BooleanField(default=True)
        ),
        migrations.AddField(
            model_name="couponinvoiceversion",
            name="automatic",
            field=models.BooleanField(default=False),
        ),
    ]
