# Generated by Django 2.1.7 on 2019-04-03 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("ecommerce", "0002_coupon_additional_fields")]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=512, unique=True)),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="CouponPayment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "payment_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("credit_card", "credit_card"),
                            ("purchase_order", "purchase_order"),
                        ],
                        max_length=128,
                        null=True,
                    ),
                ),
                ("payment_id", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ecommerce.Company",
                    ),
                ),
                (
                    "invoice_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ecommerce.CouponInvoiceVersion",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
    ]
