# Generated by Django 2.1.7 on 2019-04-04 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("ecommerce", "0002_coupon_additional_fields")]

    operations = [
        migrations.RenameField("CouponInvoiceVersion", "invoice", "payment"),
        migrations.RenameField("Coupon", "invoice", "payment"),
        migrations.RenameField("CouponVersion", "invoice_version", "payment_version"),
        migrations.AlterField(
            "CouponInvoice", "tag", models.CharField(max_length=256, unique=True)
        ),
        migrations.RenameField("CouponInvoice", "tag", "name"),
        migrations.RenameModel("CouponInvoice", "CouponPayment"),
        migrations.RenameModel("CouponInvoiceVersion", "CouponPaymentVersion"),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=512, unique=True)),
            ],
            options={"abstract": False},
        ),
        migrations.AddField(
            model_name="couponpaymentversion",
            name="payment_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("credit_card", "credit_card"),
                    ("purchase_order", "purchase_order"),
                    ("marketing", "marketing"),
                    ("sales", "sales"),
                ],
                max_length=128,
                null=True,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="couponpaymentversion",
            name="payment_transaction",
            field=models.CharField(blank=True, max_length=256, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="couponpaymentversion",
            name="tag",
            field=models.CharField(blank=True, max_length=256, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="couponpaymentversion",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="ecommerce.Company",
            ),
            preserve_default=False,
        ),
        migrations.RemoveIndex(
            model_name="couponpaymentversion", name="ecommerce_c_created_4de91c_idx"
        ),
        migrations.AddIndex(
            model_name="couponpaymentversion",
            index=models.Index(
                fields=["created_on"], name="ecommerce_c_created_0948e4_idx"
            ),
        ),
    ]
