# Generated by Django 2.1.7 on 2019-04-24 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("ecommerce", "0005_dataconsentagreement")]

    operations = [
        migrations.AlterField(
            model_name="couponpaymentversion",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="versions",
                to="ecommerce.CouponPayment",
            ),
        ),
        migrations.AlterField(
            model_name="couponversion",
            name="coupon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="versions",
                to="ecommerce.Coupon",
            ),
        ),
    ]
