# Generated by Django 2.1.7 on 2019-04-25 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("ecommerce", "0006_versions_related_names")]

    operations = [
        migrations.CreateModel(
            name="BulkEnrollmentDelivery",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254)),
                (
                    "product_coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ecommerce.CouponEligibility",
                    ),
                ),
            ],
            options={"abstract": False},
        )
    ]
