# Generated by Django 2.1.7 on 2019-05-01 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("ecommerce", "0008_unique")]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="content_type",
            field=models.ForeignKey(
                help_text="content_object is a link to either a CourseRun or a Program",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="contenttypes.ContentType",
            ),
        )
    ]
