# Generated by Django 2.1.7 on 2019-05-08 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("ecommerce", "0009_help_text")]

    operations = [
        migrations.AlterUniqueTogether(
            name="courserunenrollment", unique_together=set()
        ),
        migrations.RemoveField(model_name="courserunenrollment", name="order"),
        migrations.RemoveField(model_name="courserunenrollment", name="run"),
        migrations.DeleteModel(name="CourseRunEnrollment"),
    ]
