# Generated by Django 2.1.7 on 2019-05-15 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("ecommerce", "0010_remove_ecommerce_course_run_enrollment")]

    operations = [
        migrations.RenameModel(
            old_name="BulkEnrollmentDelivery", new_name="ProductCouponAssignment"
        )
    ]
