# Generated by Django 2.1.7 on 2019-06-26 19:04
import logging

from django.db import migrations, models

log = logging.getLogger()


class Migration(migrations.Migration):
    def backpopulate_readable_id(apps, schema_editor):
        """
        Set the readable_id for existing ProductVersions.
        """
        ProductVersion = apps.get_model("ecommerce", "ProductVersion")
        CourseRun = apps.get_model("courses", "CourseRun")
        Program = apps.get_model("courses", "Program")

        for version in (
            ProductVersion.objects.filter(text_id=None).order_by("id").iterator()
        ):
            if version.product.content_type.model == "program":
                version.text_id = Program.objects.get(
                    id=version.product.object_id
                ).readable_id
            elif version.product.content_type.model == "courserun":
                version.text_id = CourseRun.objects.get(
                    id=version.product.object_id
                ).courseware_id
            else:
                log.error(
                    f"No matching readable_id found for ProductVersion %s",
                    str(version.id),
                )
            version.save()

    dependencies = [("ecommerce", "0013_coupon_assignment_email_index")]

    operations = [
        migrations.AddField(
            model_name="productversion",
            name="text_id",
            field=models.TextField(null=True),
        ),
        migrations.RunPython(backpopulate_readable_id, migrations.RunPython.noop),
    ]
