# Generated by Django 2.2.3 on 2019-07-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("ecommerce", "0015_db_protect")]

    operations = [
        migrations.AlterField(
            model_name="couponpaymentversion",
            name="payment_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("credit_card", "credit_card"),
                    ("purchase_order", "purchase_order"),
                    ("marketing", "marketing"),
                    ("sales", "sales"),
                    ("staff", "staff"),
                ],
                max_length=128,
                null=True,
            ),
        )
    ]
