# Generated by Django 2.2.3 on 2019-09-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("ecommerce", "0017_order_total_price_paid")]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="If it is unchecked then users will not be able to load the product on the checkout page.",
            ),
        )
    ]
