# Generated by Django 2.2.4 on 2019-09-17 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("ecommerce", "0018_product_is_active")]

    operations = [
        migrations.AlterField(
            model_name="couponpaymentversion",
            name="amount",
            field=models.DecimalField(
                decimal_places=5,
                help_text="Percent discount for a coupon. Between 0 and 1.",
                max_digits=20,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
            ),
        )
    ]
