# Generated by Django 2.2.4 on 2019-10-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("ecommerce", "0020_add_bulk_coupon_assignment")]

    operations = [
        migrations.AddField(
            model_name="bulkcouponassignment",
            name="assignment_sheet_id",
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="bulkcouponassignment",
            name="coupons_assigned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bulkcouponassignment",
            name="messages_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bulkcouponassignment",
            name="updated_on",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
