# Generated by Django 2.2.4 on 2019-11-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("ecommerce", "0020_add_bulk_coupon_assignment")]

    operations = [
        migrations.AddField(
            model_name="bulkcouponassignment",
            name="assignment_sheet_id",
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="bulkcouponassignment",
            name="assignments_completed_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bulkcouponassignment",
            name="assignments_started_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bulkcouponassignment",
            name="message_delivery_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bulkcouponassignment",
            name="updated_on",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="productcouponassignment",
            name="message_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("delivered", "delivered"),
                    ("failed", "failed"),
                    ("opened", "opened"),
                    ("clicked", "clicked"),
                ],
                max_length=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="productcouponassignment",
            name="message_status_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
