# Generated by Django 2.2.4 on 2019-10-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("ecommerce", "0021_bulk_coupon_assignment_from_sheets")]

    operations = [
        migrations.RemoveField(
            model_name="bulkcouponassignment", name="coupons_assigned"
        ),
        migrations.RemoveField(model_name="bulkcouponassignment", name="messages_sent"),
        migrations.AddField(
            model_name="bulkcouponassignment",
            name="assignments_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bulkcouponassignment",
            name="assignments_started",
            field=models.BooleanField(default=False),
        ),
    ]
