# Generated by Django 2.2.8 on 2020-02-07 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0024_programrun"),
        ("ecommerce", "0024_add_product_visible_in_bulk_form_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="basketitem",
            name="program_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.ProgramRun",
            ),
        ),
        migrations.AddField(
            model_name="couponeligibility",
            name="program_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="courses.ProgramRun",
            ),
        ),
        migrations.CreateModel(
            name="ProgramRunLine",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "line",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programrunline",
                        to="ecommerce.Line",
                    ),
                ),
                (
                    "program_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.ProgramRun",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
    ]
