# Generated by Django 2.2.10 on 2020-03-05 17:55

from django.db import migrations, models


def backfill_last_assignment_date(apps, schema_editor):
    """
    Backfills the last_assignment_date field value using most recently created ProductCouponAssignment
    associated with each BulkCouponAssignment
    """
    BulkCouponAssignment = apps.get_model("ecommerce", "BulkCouponAssignment")
    for bulk_assignment in BulkCouponAssignment.objects.exclude(
        assignment_sheet_id=None
    ):
        most_recent_assignment = bulk_assignment.assignments.order_by(
            "created_on"
        ).first()
        if most_recent_assignment:
            bulk_assignment.last_assignment_date = most_recent_assignment.created_on
            bulk_assignment.save()


class Migration(migrations.Migration):

    dependencies = [("ecommerce", "0028_include_future_runs_default")]

    operations = [
        migrations.RenameField(
            model_name="bulkcouponassignment",
            old_name="assignment_sheet_last_modified",
            new_name="sheet_last_modified_date",
        ),
        migrations.AddField(
            model_name="bulkcouponassignment",
            name="last_assignment_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(
            backfill_last_assignment_date, reverse_code=migrations.RunPython.noop
        ),
    ]
