# Generated by Django 2.2.10 on 2020-03-13 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0026_nullify_expiration_date"),
        ("ecommerce", "0029_bulk_assignment_date_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="LineRunSelection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_selections",
                        to="ecommerce.Line",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.CourseRun",
                    ),
                ),
            ],
            options={"unique_together": {("line", "run")}},
        )
    ]
