# Generated by Django 2.2.10 on 2020-11-04 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("ecommerce", "0030_linerunselection")]

    operations = [
        migrations.AddField(
            model_name="productcouponassignment",
            name="original_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        )
    ]
