# Generated by Django 3.2.11 on 2022-02-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("ecommerce", "0032_add_all_courses_data_consent_flag")]

    operations = [
        migrations.AlterField(
            model_name="orderaudit",
            name="data_after",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="orderaudit",
            name="data_before",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="receipt", name="data", field=models.JSONField()
        ),
    ]
