# Generated by Django 3.2.15 on 2022-11-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0034_productversion_requires_enrollment_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="couponpaymentversion",
            name="discount_type",
            field=models.CharField(
                choices=[
                    ("percent-off", "percent-off"),
                    ("dollars-off", "dollars-off"),
                ],
                default="percent-off",
                max_length=30,
            ),
        ),
    ]
