# Generated by Django 3.2.15 on 2022-12-02 16:22

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0036_amount_validations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcouponassignment",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AddIndex(
            model_name="productcouponassignment",
            index=models.Index(
                django.db.models.functions.text.Upper("email"),
                condition=models.Q(("redeemed", False)),
                name="uppercased_email_idx",
            ),
        ),
    ]
