# Generated by Django 3.2.20 on 2023-08-29 12:38

from django.db import migrations, models


def populate_is_private(apps, schema_editor):
    """
    Inverts and Migrates `Product.visible_in_bulk_form` field data to `Product.is_private`
    as we will remove `Product.visible_in_bulk_form`.
    """
    Product = apps.get_model("ecommerce", "Product")
    Product.objects.all().update(
        is_private=models.Case(
            models.When(visible_in_bulk_form=False, then=models.Value(True)),
            default=models.Value(False),
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0037_product_coupon_assignment_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_private",
            field=models.BooleanField(
                default=False,
                help_text="Products can be Private or Public. Public products are listed in the product drop-down on the bulk purchase form at /ecommerce/bulk.",
            ),
        ),
        migrations.RunPython(
            populate_is_private, reverse_code=migrations.RunPython.noop
        ),
    ]
