# Generated by Django 3.2.21 on 2023-09-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0038_rename_visible_in_bulk_form_product_is_private"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxRate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("country_code", models.CharField(max_length=2)),
                ("tax_rate", models.DecimalField(decimal_places=4, max_digits=6)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
