# Generated by Django 3.2.21 on 2023-09-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0038_rename_visible_in_bulk_form_product_is_private"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxRate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("country_code", models.CharField(max_length=2)),
                ("tax_rate", models.DecimalField(decimal_places=4, max_digits=6)),
                (
                    "tax_rate_name",
                    models.CharField(default="VAT", max_length=100, null=True),
                ),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="tax_country_code",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="tax_rate",
            field=models.DecimalField(
                blank=True, decimal_places=4, default=0, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="tax_rate_name",
            field=models.CharField(default="VAT", max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name="taxrate",
            constraint=models.UniqueConstraint(
                fields=("country_code",), name="unique_country"
            ),
        ),
    ]
