# Generated by Django 3.2.20 on 2023-08-29 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0038_product_is_private"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="visible_in_bulk_form",
        ),
    ]
