# Generated by Django 3.2.21 on 2023-09-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0040_add_name_field_for_tax_rates"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="tax_country_code",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="tax_rate",
            field=models.DecimalField(
                blank=True, decimal_places=4, default=0, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="tax_rate_name",
            field=models.CharField(default="VAT", max_length=100, null=True),
        ),
    ]
