# Generated by Django 4.2.9 on 2024-04-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0041_alter_coupon_coupon_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="coupon_code",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
