# Generated by Django 4.2.16 on 2024-10-27 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("ecommerce", "0043_remove_extra_spaces_text_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="content_type",
            field=models.ForeignKey(
                help_text="content_object is a link to either a CourseRun or a Program",
                limit_choices_to=models.Q(
                    models.Q(("app_label", "courses"), ("model", "courserun")),
                    models.Q(("app_label", "courses"), ("model", "program")),
                    _connector="OR",
                ),
                on_delete=django.db.models.deletion.PROTECT,
                to="contenttypes.contenttype",
            ),
        ),
    ]
