# Generated by Django 5.2.16 on 2026-08-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0044_only_sellable_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="gateway_type",
            field=models.CharField(
                choices=[("CyberSource", "CyberSource"), ("Stripe", "Stripe")],
                default="CyberSource",
                help_text="The payment gateway that processed this order.",
                max_length=30,
            ),
        ),
    ]
