# Generated by Django 5.2.16 on 2026-08-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0045_order_gateway_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="stripe_checkout_session_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="The Stripe checkout session this order was sent to, recorded before the learner is redirected so the payment can be reconciled later.",
                max_length=255,
                null=True,
            ),
        ),
    ]
