# Generated by Django 4.2.30 on 2026-04-10 10:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courseware", "0004_add_courseware_related_names"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="openedxapiauth",
            new_name="courseware__user_id_7b66fa_idx",
            old_fields=("user", "access_token_expires_on"),
        ),
    ]
