# This file was generated by django-aqueduct (codegen v2).
# Regenerate with `manage.py generate_aqueduct_settings`.
#
# Code inside `# >>> aqueduct:generated:*` regions is overwritten on every run.
# Add validators and overrides inside `# >>> aqueduct:preserved:*` regions
# (or anywhere outside a generated region) — they survive regeneration.


"""Typed, validated Django settings for mitxpro, powered by django-aqueduct.

This module is the pydantic counterpart of ``mitxpro/settings.py``. It is
**not** used by default: the app keeps ``mitxpro.settings`` as its settings
module everywhere it runs today. It only takes effect via
``DJANGO_SETTINGS_MODULE=mitxpro.settings_aqueduct`` (or
``mitxpro.settings_aqueduct_dev`` for the Vault-backed dev variant below).

The ``aqueduct:generated:*`` regions are produced by codegen v2's static AST
discovery (``manage.py generate_aqueduct_settings``, configured in
``[tool.aqueduct]`` in pyproject.toml) and are rewritten on regeneration.
Static discovery recovers the env-var aliases mitxpro uses systematically
(``SITE_BASE_URL`` is configured by ``MITXPRO_BASE_URL``, etc.) as
``validation_alias`` declarations. Hand refinements live in the
``aqueduct:preserved:*`` region and everything outside the generated
regions; both survive regeneration. Parity with the legacy module is policed
by ``manage.py check_aqueduct_settings``.
"""
# >>> aqueduct:generated:imports
from __future__ import annotations

import ast
import json
import logging
import platform
from typing import Annotated, Any

from mitol.common.envs import get_features, get_string
from pydantic import AliasChoices, Field, field_validator
from pydantic_settings import BaseSettings, NoDecode, SettingsConfigDict
from redbeat import RedBeatScheduler

# <<< aqueduct:generated:imports

# ---------------------------------------------------------------------------
# Hand-maintained imports and constants. Everything outside the
# `aqueduct:generated:*` regions survives regeneration.
# ---------------------------------------------------------------------------
import os
import pathlib
from datetime import timedelta
from urllib.parse import urljoin, urlparse
from zoneinfo import ZoneInfo

from celery.schedules import crontab
from django.core.exceptions import ImproperlyConfigured
from django_aqueduct import derivations as dv
from django_aqueduct.sources.dev import vault_source_from_env
from mitol.observability.settings.logging import LOGGING as MITOL_LOGGING
from pydantic import model_validator
from pydantic_settings import PydanticBaseSettingsSource

from mitxpro.celery_utils import OffsettingSchedule

# Kept as a module constant (in addition to the generated VERSION field) so the
# shims can `from mitxpro.aqueduct_settings import VERSION` to init Sentry
# before the model is constructed, mirroring mitxpro/settings.py.
VERSION = "0.195.2"

# mitxpro/settings.py computes BASE_DIR as the parent of the directory that
# contains it. This module lives in the same directory, so the same
# computation yields the same project root.
BASE_DIR = str(pathlib.Path(__file__).resolve().parent.parent)


class AqueductSettings(BaseSettings):
    """Typed Django settings model generated by django-aqueduct."""

    model_config = SettingsConfigDict(env_prefix="", extra="allow")





    # >>> aqueduct:generated:fields
    # ===== mitol.authentication.settings.djoser_settings =====
    DJOSER: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    MITOL_AUTHENTICATION_REPLY_TO_ADDRESS: str = Field(
        default="webmaster@localhost",
        validation_alias=AliasChoices("MITOL_AUTHENTICATION_REPLY_TO_ADDRESS"),
    )
    # ===== mitol.common.settings.webpack =====
    WEBPACK_DEV_SERVER_HOST: str = Field(
        default="", validation_alias=AliasChoices("WEBPACK_DEV_SERVER_HOST")
    )
    WEBPACK_DEV_SERVER_PORT: int | None = Field(
        default=None, validation_alias=AliasChoices("WEBPACK_DEV_SERVER_PORT")
    )
    WEBPACK_DISABLE_LOADER_STATS: bool = Field(
        default=False, validation_alias=AliasChoices("WEBPACK_DISABLE_LOADER_STATS")
    )
    WEBPACK_USE_DEV_SERVER: bool = Field(
        default=False, validation_alias=AliasChoices("WEBPACK_USE_DEV_SERVER")
    )
    # ===== mitol.digitalcredentials.settings =====
    MITOL_DIGITAL_CREDENTIALS_AUTH_TYPE: str | None = Field(
        default=None,
        validation_alias=AliasChoices("MITOL_DIGITAL_CREDENTIALS_AUTH_TYPE"),
    )  # REDACTED: name looks secret-like — set via a source, not here
    MITOL_DIGITAL_CREDENTIALS_DEEP_LINK_URL: str | None = Field(
        default=None,
        validation_alias=AliasChoices("MITOL_DIGITAL_CREDENTIALS_DEEP_LINK_URL"),
    )  # REDACTED: name looks secret-like — set via a source, not here
    MITOL_DIGITAL_CREDENTIALS_HMAC_SECRET: str | None = Field(
        default=None,
        validation_alias=AliasChoices("MITOL_DIGITAL_CREDENTIALS_HMAC_SECRET"),
    )  # REDACTED: name looks secret-like — set via a source, not here
    MITOL_DIGITAL_CREDENTIALS_VERIFY_SERVICE_BASE_URL: str | None = Field(
        default=None,
        validation_alias=AliasChoices("MITOL_DIGITAL_CREDENTIALS_VERIFY_SERVICE_BASE_URL"),  # noqa: E501
    )  # REDACTED: name looks secret-like — set via a source, not here
    # ===== mitol.olposthog.settings.olposthog =====
    POSTHOG_API_HOST: str = Field(
        default="https://us.posthog.com",
        validation_alias=AliasChoices("POSTHOG_API_HOST"),
    )
    POSTHOG_CIRCUIT_BREAKER_COOLDOWN_SECONDS: int = Field(
        default=60,
        validation_alias=AliasChoices("POSTHOG_CIRCUIT_BREAKER_COOLDOWN_SECONDS"),
    )
    POSTHOG_CIRCUIT_BREAKER_TRIP_THRESHOLD_SECONDS: int = Field(
        default=6,
        validation_alias=AliasChoices("POSTHOG_CIRCUIT_BREAKER_TRIP_THRESHOLD_SECONDS"),
    )
    POSTHOG_ENABLED: bool = Field(
        default=False, validation_alias=AliasChoices("POSTHOG_ENABLED")
    )
    POSTHOG_FEATURE_FLAG_REQUEST_TIMEOUT_MS: int = Field(
        default=3000,
        validation_alias=AliasChoices("POSTHOG_FEATURE_FLAG_REQUEST_TIMEOUT_MS"),
    )
    POSTHOG_MAX_RETRIES: int = Field(
        default=3, validation_alias=AliasChoices("POSTHOG_MAX_RETRIES")
    )
    POSTHOG_PERSONAL_API_KEY: str | None = Field(
        default=None, validation_alias=AliasChoices("POSTHOG_PERSONAL_API_KEY")
    )  # REDACTED: name looks secret-like — set via a source, not here
    POSTHOG_POLL_INTERVAL: int = Field(
        default=300, validation_alias=AliasChoices("POSTHOG_POLL_INTERVAL")
    )
    POSTHOG_PROJECT_API_KEY: str | None = Field(
        default=None, validation_alias=AliasChoices("POSTHOG_PROJECT_API_KEY")
    )  # REDACTED: name looks secret-like — set via a source, not here
    # ===== mitxpro.settings =====
    ADMINS: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    ADMIN_EMAIL: str = Field(
        ...,
        validation_alias=AliasChoices("MITXPRO_ADMIN_EMAIL"),
        description="e-mail configurable admins",
    )
    ALLOWED_HOSTS: Annotated[list[Any], NoDecode] = Field(default_factory=lambda: ["*"])
    ANYMAIL: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    AUTHENTICATION_BACKENDS: tuple[Any, ...] = Field(
        default=(
            "social_core.backends.email.EmailAuth",
            "oauth2_provider.backends.OAuth2Backend",
            "django.contrib.auth.backends.ModelBackend",
        ),
        description="the only declaration of AUTHENTICATION_BACKENDS: a dead duplicate earlier\nin this file (SAML/MicroMasters backends, dead since\nauthentication.backends.micromasters was removed and no SOCIAL_AUTH_SAML_*\nconfig was ever added), which this declaration silently shadowed, has\nbeen deleted",  # noqa: E501
    )  # TODO: refine type
    AUTH_CHANGE_EMAIL_TTL_IN_MINUTES: int = Field(
        default_factory=lambda: 60 * 24,
        validation_alias=AliasChoices("AUTH_CHANGE_EMAIL_TTL_IN_MINUTES"),
    )
    AUTH_USER_MODEL: str = Field(
        default="users.User", description="configure a custom user model"
    )
    AWS_ACCESS_KEY_ID: str | None = Field(
        default=None, validation_alias=AliasChoices("AWS_ACCESS_KEY_ID")
    )  # REDACTED: name looks secret-like — set via a source, not here
    AWS_QUERYSTRING_AUTH: bool = Field(
        default=False, validation_alias=AliasChoices("AWS_QUERYSTRING_AUTH")
    )
    AWS_S3_CUSTOM_DOMAIN: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    AWS_SECRET_ACCESS_KEY: str | None = Field(
        default=None, validation_alias=AliasChoices("AWS_SECRET_ACCESS_KEY")
    )  # REDACTED: name looks secret-like — set via a source, not here
    AWS_STORAGE_BUCKET_NAME: str | None = Field(
        default=None, validation_alias=AliasChoices("AWS_STORAGE_BUCKET_NAME")
    )
    BASE_DIR: Any = Field(
        default=None,
        description="Build paths inside the project like this: os.path.join(BASE_DIR, ...)",  # noqa: E501
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    BASKET_EXPIRY_DAYS: int = Field(
        default=15, validation_alias=AliasChoices("BASKET_EXPIRY_DAYS")
    )
    BLOG_CACHE_TIMEOUT: int = Field(
        default_factory=lambda: 60 * 60 * 24,
        validation_alias=AliasChoices("BLOG_CACHE_TIMEOUT"),
    )
    CACHES: Any = Field(
        default=None, description="django cache back-ends"
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    CANONICAL_HOSTNAME_REDIRECT_ENABLED: bool = Field(
        default=False,
        validation_alias=AliasChoices("CANONICAL_HOSTNAME_REDIRECT_ENABLED"),
    )
    CELERY_ACCEPT_CONTENT: Annotated[list[Any], NoDecode] = Field(
        default_factory=lambda: ["json"]
    )
    CELERY_BEAT_SCHEDULE: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    CELERY_BEAT_SCHEDULER: Any = Field(
        default_factory=lambda: RedBeatScheduler
    )  # TODO: refine type
    CELERY_BROKER_URL: str | None = Field(
        default=None, validation_alias=AliasChoices("CELERY_BROKER_URL")
    )  # REDACTED: name looks secret-like — set via a source, not here
    CELERY_REDBEAT_REDIS_URL: str | None = Field(
        default=None
    )  # REDACTED: name looks secret-like — set via a source, not here
    CELERY_RESULT_BACKEND: str | None = Field(
        default=None, validation_alias=AliasChoices("CELERY_RESULT_BACKEND")
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    CELERY_RESULT_SERIALIZER: str = Field(default="json")
    CELERY_TASK_ALWAYS_EAGER: bool = Field(
        default=False, validation_alias=AliasChoices("CELERY_TASK_ALWAYS_EAGER")
    )
    CELERY_TASK_EAGER_PROPAGATES: bool = Field(
        default=True, validation_alias=AliasChoices("CELERY_TASK_EAGER_PROPAGATES")
    )
    CELERY_TASK_SEND_SENT_EVENT: bool = Field(default=True)
    CELERY_TASK_SERIALIZER: str = Field(default="json")
    CELERY_TASK_TRACK_STARTED: bool = Field(default=True)
    CELERY_TIMEZONE: str = Field(default="UTC")
    CERTIFICATE_CREATION_DELAY_IN_HOURS: int = Field(
        default=48, validation_alias=AliasChoices("CERTIFICATE_CREATION_DELAY_IN_HOURS")
    )
    CLOUDFRONT_DIST: str | None = Field(
        default=None, validation_alias=AliasChoices("CLOUDFRONT_DIST")
    )
    COUPON_REQUEST_SHEET_ID: str | None = Field(
        default=None, validation_alias=AliasChoices("COUPON_REQUEST_SHEET_ID")
    )
    CRON_BASKET_DELETE_DAYS: str = Field(
        default="*", validation_alias=AliasChoices("CRON_BASKET_DELETE_DAYS")
    )
    CRON_BASKET_DELETE_HOURS: str = Field(
        default=0, validation_alias=AliasChoices("CRON_BASKET_DELETE_HOURS")
    )
    CRON_COURSERUN_SYNC_DAYS: str | None = Field(
        default=None, validation_alias=AliasChoices("CRON_COURSERUN_SYNC_DAYS")
    )
    CRON_COURSERUN_SYNC_HOURS: str = Field(
        default=0, validation_alias=AliasChoices("CRON_COURSERUN_SYNC_HOURS")
    )
    CRON_COURSE_CERTIFICATES_DAYS: str | None = Field(
        default=None, validation_alias=AliasChoices("CRON_COURSE_CERTIFICATES_DAYS")
    )
    CRON_COURSE_CERTIFICATES_HOURS: str = Field(
        default=0, validation_alias=AliasChoices("CRON_COURSE_CERTIFICATES_HOURS")
    )
    CRON_EXTERNAL_COURSERUN_SYNC_DAYS: str | None = Field(
        default=None, validation_alias=AliasChoices("CRON_EXTERNAL_COURSERUN_SYNC_DAYS")
    )
    CRON_EXTERNAL_COURSERUN_SYNC_HOURS: str = Field(
        default="0", validation_alias=AliasChoices("CRON_EXTERNAL_COURSERUN_SYNC_HOURS")
    )
    CSRF_TRUSTED_ORIGINS: Annotated[list[str], NoDecode] = Field(
        default_factory=lambda: [],
        validation_alias=AliasChoices("CSRF_TRUSTED_ORIGINS"),
    )
    CYBERSOURCE_ACCESS_KEY: str | None = Field(
        default=None,
        validation_alias=AliasChoices("CYBERSOURCE_ACCESS_KEY"),
        description="Cybersource",
    )  # REDACTED: name looks secret-like — set via a source, not here
    CYBERSOURCE_EXPORT_SERVICE_ADDRESS_OPERATOR: str = Field(
        default="AND",
        validation_alias=AliasChoices("CYBERSOURCE_EXPORT_SERVICE_ADDRESS_OPERATOR"),
    )
    CYBERSOURCE_EXPORT_SERVICE_ADDRESS_WEIGHT: str = Field(
        default="high",
        validation_alias=AliasChoices("CYBERSOURCE_EXPORT_SERVICE_ADDRESS_WEIGHT"),
    )
    CYBERSOURCE_EXPORT_SERVICE_NAME_WEIGHT: str = Field(
        default="high",
        validation_alias=AliasChoices("CYBERSOURCE_EXPORT_SERVICE_NAME_WEIGHT"),
    )
    CYBERSOURCE_EXPORT_SERVICE_SANCTIONS_LISTS: str | None = Field(
        default=None,
        validation_alias=AliasChoices("CYBERSOURCE_EXPORT_SERVICE_SANCTIONS_LISTS"),
    )
    CYBERSOURCE_INQUIRY_LOG_NACL_ENCRYPTION_KEY: str | None = Field(
        default=None,
        validation_alias=AliasChoices("CYBERSOURCE_INQUIRY_LOG_NACL_ENCRYPTION_KEY"),
    )  # REDACTED: name looks secret-like — set via a source, not here
    CYBERSOURCE_MERCHANT_ID: str | None = Field(
        default=None, validation_alias=AliasChoices("CYBERSOURCE_MERCHANT_ID")
    )
    CYBERSOURCE_PROFILE_ID: str | None = Field(
        default=None, validation_alias=AliasChoices("CYBERSOURCE_PROFILE_ID")
    )
    CYBERSOURCE_SECURE_ACCEPTANCE_URL: str | None = Field(
        default=None, validation_alias=AliasChoices("CYBERSOURCE_SECURE_ACCEPTANCE_URL")
    )
    CYBERSOURCE_SECURITY_KEY: str | None = Field(
        default=None, validation_alias=AliasChoices("CYBERSOURCE_SECURITY_KEY")
    )
    CYBERSOURCE_TRANSACTION_KEY: str | None = Field(
        default=None, validation_alias=AliasChoices("CYBERSOURCE_TRANSACTION_KEY")
    )
    CYBERSOURCE_WSDL_URL: str | None = Field(
        default=None, validation_alias=AliasChoices("CYBERSOURCE_WSDL_URL")
    )
    DATABASES: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    DEBUG: bool = Field(
        default=False,
        validation_alias=AliasChoices("DEBUG"),
        description="SECURITY WARNING: don't run with debug turned on in production!",
    )
    DEFAULT_AUTO_FIELD: str = Field(default="django.db.models.AutoField")
    DEFAULT_DATABASE_CONFIG: Any = Field(
        default=None,
        description="Database\nhttps://docs.djangoproject.com/en/2.0/ref/settings/#databases",  # noqa: E501
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    DEFAULT_FROM_EMAIL: str = Field(
        default="webmaster@localhost",
        validation_alias=AliasChoices("MITXPRO_FROM_EMAIL"),
    )
    DEFERRAL_REQUEST_WORKSHEET_ID: str | None = Field(
        default=None, validation_alias=AliasChoices("DEFERRAL_REQUEST_WORKSHEET_ID")
    )
    DIGITAL_CREDENTIALS_DEEP_LINK_URL: str | None = Field(
        default=None,
        validation_alias=AliasChoices("DIGITAL_CREDENTIALS_DEEP_LINK_URL"),
        description="Digital Credentials",
    )  # REDACTED: name looks secret-like — set via a source, not here
    DIGITAL_CREDENTIALS_ISSUER_ID: str | None = Field(
        default=None, validation_alias=AliasChoices("DIGITAL_CREDENTIALS_ISSUER_ID")
    )  # REDACTED: name looks secret-like — set via a source, not here
    DIGITAL_CREDENTIALS_SUPPORTED_RUNS: Annotated[list[str] | None, NoDecode] = Field(
        default=None,
        validation_alias=AliasChoices("DIGITAL_CREDENTIALS_SUPPORTED_RUNS"),
        description="TODO: This setting is meant to be temporary and it should be removed once we decide to support digital credentials  # noqa: FIX002, TD002, TD003\nfor all courses/programs.",
    )  # REDACTED: name looks secret-like — set via a source, not here
    DIGITAL_CREDENTIALS_VERIFICATION_METHOD: str | None = Field(
        default=None,
        validation_alias=AliasChoices("DIGITAL_CREDENTIALS_VERIFICATION_METHOD"),
    )  # REDACTED: name looks secret-like — set via a source, not here
    DJANGO_LOG_LEVEL: str = Field(
        default="INFO", validation_alias=AliasChoices("DJANGO_LOG_LEVEL")
    )
    DRIVE_API_PROJECT_ID: str | None = Field(
        default=None, validation_alias=AliasChoices("DRIVE_API_PROJECT_ID")
    )
    DRIVE_CLIENT_ID: str | None = Field(
        default=None, validation_alias=AliasChoices("DRIVE_CLIENT_ID")
    )
    DRIVE_CLIENT_SECRET: str | None = Field(
        default=None, validation_alias=AliasChoices("DRIVE_CLIENT_SECRET")
    )  # REDACTED: name looks secret-like — set via a source, not here
    DRIVE_OUTPUT_FOLDER_ID: str | None = Field(
        default=None, validation_alias=AliasChoices("DRIVE_OUTPUT_FOLDER_ID")
    )
    DRIVE_SERVICE_ACCOUNT_CREDS: str | None = Field(
        default=None,
        validation_alias=AliasChoices("DRIVE_SERVICE_ACCOUNT_CREDS"),
        description="Sheets settings",
    )
    DRIVE_SHARED_ID: str | None = Field(
        default=None, validation_alias=AliasChoices("DRIVE_SHARED_ID")
    )
    DRIVE_WEBHOOK_ASSIGNMENT_MAX_AGE_DAYS: int = Field(
        default=30,
        validation_alias=AliasChoices("DRIVE_WEBHOOK_ASSIGNMENT_MAX_AGE_DAYS"),
    )
    DRIVE_WEBHOOK_ASSIGNMENT_WAIT: int = Field(
        default_factory=lambda: 60 * 5,
        validation_alias=AliasChoices("DRIVE_WEBHOOK_ASSIGNMENT_WAIT"),
    )
    DRIVE_WEBHOOK_CHANNEL_ID: str = Field(
        default="mitxpro-sheets-app",
        validation_alias=AliasChoices("DRIVE_WEBHOOK_CHANNEL_ID"),
    )
    DRIVE_WEBHOOK_EXPIRATION_MINUTES: int = Field(
        default_factory=lambda: 60 * 24,
        validation_alias=AliasChoices("DRIVE_WEBHOOK_EXPIRATION_MINUTES"),
    )
    DRIVE_WEBHOOK_RENEWAL_PERIOD_MINUTES: int = Field(
        default_factory=lambda: 60 * 3,
        validation_alias=AliasChoices("DRIVE_WEBHOOK_RENEWAL_PERIOD_MINUTES"),
    )
    ECOMMERCE_FORCE_PROFILE_COUNTRY: bool = Field(
        default=False,
        validation_alias=AliasChoices("ECOMMERCE_FORCE_PROFILE_COUNTRY"),
        description="Force the country determination code to use the user's profile only\nThis is for local testing, since your IP won't belong to a country",  # noqa: E501
    )
    EDX_API_CLIENT_TIMEOUT: int = Field(
        default=60, validation_alias=AliasChoices("EDX_API_CLIENT_TIMEOUT")
    )
    EMAIL_BACKEND: str = Field(
        default="django.core.mail.backends.smtp.EmailBackend",
        validation_alias=AliasChoices("MITXPRO_EMAIL_BACKEND"),
        description="Configure e-mail settings",
    )
    EMAIL_HOST: str = Field(
        default="localhost", validation_alias=AliasChoices("MITXPRO_EMAIL_HOST")
    )
    EMAIL_HOST_PASSWORD: str | None = Field(
        default=None, validation_alias=AliasChoices("MITXPRO_EMAIL_PASSWORD")
    )  # REDACTED: name looks secret-like — set via a source, not here
    EMAIL_HOST_USER: str = Field(
        default="", validation_alias=AliasChoices("MITXPRO_EMAIL_USER")
    )
    EMAIL_PORT: int = Field(
        default=25, validation_alias=AliasChoices("MITXPRO_EMAIL_PORT")
    )
    EMAIL_SUPPORT: str | None = Field(
        default=None, validation_alias=AliasChoices("MITXPRO_SUPPORT_EMAIL")
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    EMAIL_USE_TLS: bool = Field(
        default=False, validation_alias=AliasChoices("MITXPRO_EMAIL_TLS")
    )
    ENROLLMENT_CHANGE_SHEET_ID: str | None = Field(
        default=None, validation_alias=AliasChoices("ENROLLMENT_CHANGE_SHEET_ID")
    )
    ENVIRONMENT: str = Field(..., validation_alias=AliasChoices("MITXPRO_ENVIRONMENT"))
    EXTERNAL_COURSE_SYNC_API_BASE_URL: str = Field(
        default="https://mit-xpro.emeritus-analytics.io/",
        validation_alias=AliasChoices("EXTERNAL_COURSE_SYNC_API_BASE_URL"),
    )
    EXTERNAL_COURSE_SYNC_API_KEY: str = Field(
        ..., validation_alias=AliasChoices("EXTERNAL_COURSE_SYNC_API_KEY")
    )
    EXTERNAL_COURSE_SYNC_API_REQUEST_TIMEOUT: int = Field(
        default=60,
        validation_alias=AliasChoices("EXTERNAL_COURSE_SYNC_API_REQUEST_TIMEOUT"),
    )
    EXTERNAL_COURSE_SYNC_EMAIL_RECIPIENTS: Annotated[list[str], NoDecode] = Field(
        default_factory=lambda: [],
        validation_alias=AliasChoices("EXTERNAL_COURSE_SYNC_EMAIL_RECIPIENTS"),
    )
    FEATURES: Any = Field(default_factory=lambda: get_features())  # TODO: refine type
    GA_TRACKING_ID: str = Field(
        default="", validation_alias=AliasChoices("GA_TRACKING_ID")
    )
    GOOGLE_DOMAIN_VERIFICATION_TAG_VALUE: str | None = Field(
        default=None,
        validation_alias=AliasChoices("GOOGLE_DOMAIN_VERIFICATION_TAG_VALUE"),
    )
    GTM_TRACKING_ID: str = Field(
        default="", validation_alias=AliasChoices("GTM_TRACKING_ID")
    )
    HEROKU_APP_NAME: str | None = Field(
        default=None,
        validation_alias=AliasChoices("HEROKU_APP_NAME"),
        description="this is only available to heroku review apps",
    )
    HIJACK_INSERT_BEFORE: str = Field(default="</body>", description="Hijack")
    HOSTNAME: Any = Field(
        default_factory=lambda: platform.node().split(".")[0]
    )  # TODO: refine type
    HUBSPOT_CONFIG: Any = Field(
        default_factory=lambda: {
    "HUBSPOT_NEW_COURSES_FORM_GUID": get_string(
        name="HUBSPOT_NEW_COURSES_FORM_GUID",
        default="",
        description="Form guid over hub spot for new courses email subscription form.",
    ),
    "HUBSPOT_FOOTER_FORM_GUID": get_string(
        name="HUBSPOT_FOOTER_FORM_GUID",
        default="",
        description="Form guid over hub spot for footer block.",
    ),
    "HUBSPOT_PORTAL_ID": get_string(
        name="HUBSPOT_PORTAL_ID", default="", description="Hub spot portal id."
    ),
    "HUBSPOT_CREATE_USER_FORM_ID": get_string(
        name="HUBSPOT_CREATE_USER_FORM_ID",
        default=None,
        description="Form ID for Hubspot Forms API",
    ),
    "HUBSPOT_ENTERPRISE_PAGE_FORM_ID": get_string(
        name="HUBSPOT_ENTERPRISE_PAGE_FORM_ID",
        default=None,
        description="Form ID for Hubspot for Enterprise Page",
    ),
},
    )  # TODO: refine type
    HUBSPOT_MAX_CONCURRENT_TASKS: int = Field(
        default=4, validation_alias=AliasChoices("HUBSPOT_MAX_CONCURRENT_TASKS")
    )
    HUBSPOT_PIPELINE_ID: str = Field(
        default="default", validation_alias=AliasChoices("HUBSPOT_PIPELINE_ID")
    )
    HUBSPOT_TASK_DELAY: int = Field(
        default=1000, validation_alias=AliasChoices("HUBSPOT_TASK_DELAY")
    )
    INSTALLED_APPS: tuple[Any, ...] = Field(
        default=(
            "django.contrib.admin",
            "django.contrib.auth",
            "django.contrib.contenttypes",
            "django.contrib.sessions",
            "django.contrib.messages",
            "django.contrib.staticfiles",
            "django.contrib.humanize",
            "django.contrib.sites",
            "django.contrib.sitemaps",
            "django_user_agents",
            "social_django",
            "oauth2_provider",
            "rest_framework",
            "anymail",
            "django_filters",
            "wagtail.contrib.forms",
            "wagtail.contrib.redirects",
            "wagtail.contrib.table_block",
            "wagtail.contrib.routable_page",
            "wagtail.embeds",
            "wagtail.sites",
            "users.apps.MitxproWagtailUsersAppConfig",
            "wagtail.snippets",
            "wagtail.documents",
            "wagtail.images",
            "wagtail.search",
            "wagtail.admin",
            "wagtail",
            "wagtailmetadata",
            "modelcluster",
            "taggit",
            "wagtail.api.v2",
            "robots",
            "mitxpro",
            "authentication",
            "courses",
            "mail.apps.MailApp",
            "users",
            "cms",
            "compliance",
            "courseware",
            "sheets",
            "affiliate",
            "b2b_ecommerce",
            "ecommerce",
            "hijack",
            "hijack.contrib.admin",
            "hubspot_xpro",
            "voucher",
            "maxmind",
            "mitol.hubspot_api.apps.HubspotApiApp",
            "mitol.common.apps.CommonApp",
            "mitol.observability.apps.ObservabilityConfig",
            "mitol.digitalcredentials.apps.DigitalCredentialsApp",
            "mitol.mail.apps.MailApp",
            "mitol.oauth_toolkit_extensions.apps.OAuthToolkitExtensionsApp",
            "mitol.authentication.apps.TransitionalAuthenticationApp",
            "mitol.olposthog.apps.OlPosthog",
            "health_check",
            "django_aqueduct",
        ),
        description="Application definition",
    )  # TODO: refine type
    INTERNAL_IPS: Any = Field(
        default_factory=lambda: (
    get_string(
        name="HOST_IP", default="127.0.0.1", description="This server's host IP"
    ),
),
        description="Important to define this so DEBUG works properly",
    )  # TODO: refine type
    LANGUAGE_CODE: str = Field(default="en-us")
    LOGIN_ERROR_URL: str = Field(default="/signin")
    LOGIN_REDIRECT_URL: str = Field(default="/")
    LOGIN_URL: str = Field(default="/signin")
    LOGOUT_REDIRECT_URL: str = Field(
        default="/", validation_alias=AliasChoices("LOGOUT_REDIRECT_URL")
    )
    LOG_LEVEL: str = Field(
        default="INFO",
        validation_alias=AliasChoices("MITXPRO_LOG_LEVEL"),
        description="Logging configuration",
    )
    MAILGUN_BATCH_CHUNK_SIZE: int = Field(
        default=1000, validation_alias=AliasChoices("MAILGUN_BATCH_CHUNK_SIZE")
    )
    MAILGUN_FROM_EMAIL: str = Field(
        default="no-reply@localhost",
        validation_alias=AliasChoices("MAILGUN_FROM_EMAIL"),
    )
    MAILGUN_KEY: str = Field(..., validation_alias=AliasChoices("MAILGUN_KEY"))
    MAILGUN_RECIPIENT_OVERRIDE: str | None = Field(
        default=None, validation_alias=AliasChoices("MAILGUN_RECIPIENT_OVERRIDE")
    )
    MAILGUN_SENDER_DOMAIN: str = Field(
        ..., validation_alias=AliasChoices("MAILGUN_SENDER_DOMAIN")
    )
    MEDIA_ROOT: str = Field(
        default="/var/media/", validation_alias=AliasChoices("MEDIA_ROOT")
    )
    MEDIA_URL: str = Field(default="/media/")
    MIDDLEWARE: tuple[Any, ...] = Field(
        default=(
            "django.middleware.security.SecurityMiddleware",
            "mitxpro.middleware.HostnameRedirectMiddleware",
            "django.contrib.sessions.middleware.SessionMiddleware",
            "affiliate.middleware.AffiliateMiddleware",
            "oauth2_provider.middleware.OAuth2TokenMiddleware",
            "django.middleware.common.CommonMiddleware",
            "django.middleware.csrf.CsrfViewMiddleware",
            "django.contrib.auth.middleware.AuthenticationMiddleware",
            "hijack.middleware.HijackUserMiddleware",
            "django.contrib.messages.middleware.MessageMiddleware",
            "django.middleware.clickjacking.XFrameOptionsMiddleware",
            "django.contrib.sites.middleware.CurrentSiteMiddleware",
            "django_user_agents.middleware.UserAgentMiddleware",
            "wagtail.contrib.redirects.middleware.RedirectMiddleware",
        ),
    )  # TODO: refine type
    MITOL_AUTHENTICATION_FROM_EMAIL: Any = Field(
        default=None, description="mitol-django-authenticaton"
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    MITOL_AUTHENTICATION_REPLY_TO_EMAIL: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    MITOL_COMMON_USER_FACTORY: str = Field(
        default="users.factories.UserFactory", description="mitol-django-common"
    )
    MITOL_DIGITAL_CREDENTIALS_BUILD_CREDENTIAL_FUNC: str | None = Field(
        default=None, description="mitol-django-digital-credentials"
    )  # REDACTED: name looks secret-like — set via a source, not here
    MITOL_HUBSPOT_API_ID_PREFIX: str = Field(
        default="XPRO", validation_alias=AliasChoices("MITOL_HUBSPOT_API_ID_PREFIX")
    )
    MITOL_HUBSPOT_API_PRIVATE_TOKEN: str | None = Field(
        default=None,
        validation_alias=AliasChoices("MITOL_HUBSPOT_API_PRIVATE_TOKEN"),
        description="Hubspot sync settings",
    )  # REDACTED: name looks secret-like — set via a source, not here
    MITOL_HUBSPOT_API_RETRIES: int = Field(
        default=3, validation_alias=AliasChoices("MITOL_HUBSPOT_API_RETRIES")
    )
    MITOL_MAIL_ENABLE_EMAIL_DEBUGGER: bool = Field(
        default=False, validation_alias=AliasChoices("MITOL_MAIL_ENABLE_EMAIL_DEBUGGER")
    )
    MITOL_MAIL_FORMAT_RECIPIENT_FUNC: str = Field(
        default="users.utils.format_recipient"
    )
    MITOL_MAIL_FROM_EMAIL: Any = Field(
        default=None, description="mitol-django-mail"
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    MITOL_MAIL_MESSAGE_CLASSES: Annotated[list[Any], NoDecode] = Field(
        default_factory=lambda: ["courses.messages.DigitalCredentialAvailableMessage"]
    )
    MITOL_MAIL_RECIPIENT_OVERRIDE: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    MITOL_MAIL_REPLY_TO_ADDRESS: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    MITXPRO_REGISTRATION_ACCESS_TOKEN: str | None = Field(
        default=None, validation_alias=AliasChoices("MITXPRO_REGISTRATION_ACCESS_TOKEN")
    )  # REDACTED: name looks secret-like — set via a source, not here
    MITXPRO_REPLY_TO_ADDRESS: str = Field(
        default="webmaster@localhost",
        validation_alias=AliasChoices("MITXPRO_REPLY_TO_ADDRESS"),
    )
    MITXPRO_USE_S3: bool = Field(
        default=False, validation_alias=AliasChoices("MITXPRO_USE_S3")
    )
    NOTIFICATION_EMAIL_BACKEND: str = Field(
        default="anymail.backends.mailgun.EmailBackend",
        validation_alias=AliasChoices("MITXPRO_NOTIFICATION_EMAIL_BACKEND"),
    )
    NPLUSONE_LOGGER: Any = Field(
        default_factory=lambda: logging.getLogger("nplusone"),
        description="nplusone profiler logger configuration",
    )  # TODO: refine type
    NPLUSONE_LOG_LEVEL: Any = Field(
        default_factory=lambda: logging.ERROR
    )  # TODO: refine type
    OAUTH2_PROVIDER: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    OAUTH2_PROVIDER_ACCESS_TOKEN_MODEL: str | None = Field(
        default=None, description="required for migrations"
    )  # REDACTED: name looks secret-like — set via a source, not here
    OAUTH2_PROVIDER_APPLICATION_MODEL: str = Field(
        default="oauth2_provider.Application"
    )
    OAUTH2_PROVIDER_REFRESH_TOKEN_MODEL: str | None = Field(
        default=None
    )  # REDACTED: name looks secret-like — set via a source, not here
    OPENEDX_API_BASE_URL: str = Field(
        ..., validation_alias=AliasChoices("OPENEDX_API_BASE_URL")
    )
    OPENEDX_API_CLIENT_ID: str = Field(
        ..., validation_alias=AliasChoices("OPENEDX_API_CLIENT_ID")
    )
    OPENEDX_API_CLIENT_SECRET: str = Field(
        ..., validation_alias=AliasChoices("OPENEDX_API_CLIENT_SECRET")
    )
    OPENEDX_BASE_REDIRECT_URL: str | None = Field(
        default=None, validation_alias=AliasChoices("OPENEDX_BASE_REDIRECT_URL")
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    OPENEDX_OAUTH_APP_NAME: str = Field(
        ..., validation_alias=AliasChoices("OPENEDX_OAUTH_APP_NAME")
    )
    OPENEDX_OAUTH_PROVIDER: str = Field(
        default="ol-oauth2", validation_alias=AliasChoices("OPENEDX_OAUTH_PROVIDER")
    )
    OPENEDX_SERVICE_WORKER_API_TOKEN: str | None = Field(
        default=None, validation_alias=AliasChoices("OPENEDX_SERVICE_WORKER_API_TOKEN")
    )  # REDACTED: name looks secret-like — set via a source, not here
    OPENEDX_SERVICE_WORKER_USERNAME: str | None = Field(
        default=None, validation_alias=AliasChoices("OPENEDX_SERVICE_WORKER_USERNAME")
    )
    OPENEDX_SOCIAL_LOGIN_PATH: str = Field(
        default="/auth/login/ol-oauth2/?auth_entry=login",
        validation_alias=AliasChoices("OPENEDX_SOCIAL_LOGIN_PATH"),
    )
    OPENEDX_TOKEN_EXPIRES_HOURS: int | None = Field(
        default=None, validation_alias=AliasChoices("OPENEDX_TOKEN_EXPIRES_HOURS")
    )  # REDACTED: name looks secret-like — set via a source, not here
    PASSWORD_RESET_CONFIRM_URL: str | None = Field(
        default=None,
        description="Relative URL to be used by Djoser for the link in the password reset email\n(see: http://djoser.readthedocs.io/en/stable/settings.html#password-reset-confirm-url)",  # noqa: E501
    )  # REDACTED: name looks secret-like — set via a source, not here
    REACT_GA_DEBUG: bool = Field(
        default=False, validation_alias=AliasChoices("REACT_GA_DEBUG")
    )
    RECAPTCHA_SECRET_KEY: str | None = Field(
        default=None, validation_alias=AliasChoices("RECAPTCHA_SECRET_KEY")
    )  # REDACTED: name looks secret-like — set via a source, not here
    RECAPTCHA_SITE_KEY: str = Field(
        default="", validation_alias=AliasChoices("RECAPTCHA_SITE_KEY")
    )
    REDISCLOUD_URL: str | None = Field(
        default=None,
        validation_alias=AliasChoices("REDISCLOUD_URL"),
        description="Redis",
    )
    REFUND_REQUEST_WORKSHEET_ID: str = Field(
        default="0", validation_alias=AliasChoices("REFUND_REQUEST_WORKSHEET_ID")
    )
    REPAIR_COURSEWARE_USERS_FREQUENCY: int = Field(
        default_factory=lambda: 60 * 30,
        validation_alias=AliasChoices("REPAIR_COURSEWARE_USERS_FREQUENCY"),
    )
    REPAIR_COURSEWARE_USERS_OFFSET: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    REST_FRAMEWORK: Annotated[dict[str, Any], NoDecode] = Field(
        default_factory=lambda: {
            "DEFAULT_AUTHENTICATION_CLASSES": (
                "rest_framework.authentication.SessionAuthentication",
                "oauth2_provider.contrib.rest_framework.OAuth2Authentication",
            ),
            "DEFAULT_PERMISSION_CLASSES": (
                "rest_framework.permissions.IsAuthenticated",
            ),
            "EXCEPTION_HANDLER": "mitxpro.exceptions.exception_handler",
            "TEST_REQUEST_DEFAULT_FORMAT": "json",
        },
        description="DRF configuration",
    )
    RETRY_FAILED_EDX_ENROLLMENT_FREQUENCY: int = Field(
        default_factory=lambda: 60 * 30,
        validation_alias=AliasChoices("RETRY_FAILED_EDX_ENROLLMENT_FREQUENCY"),
    )
    ROBOTS_CACHE_TIMEOUT: int = Field(
        default_factory=lambda: 60 * 60 * 24,
        validation_alias=AliasChoices("ROBOTS_CACHE_TIMEOUT"),
    )
    ROBOTS_USE_HOST: bool = Field(default=False, description="django-robots")
    ROOT_URLCONF: str = Field(default="mitxpro.urls")
    SECRET_KEY: str = Field(
        ...,
        validation_alias=AliasChoices("SECRET_KEY"),
        description="SECURITY WARNING: keep the secret key used in production secret!",
    )
    SECURE_SSL_HOST: str | None = Field(
        default=None, validation_alias=AliasChoices("MITXPRO_SECURE_SSL_HOST")
    )
    SECURE_SSL_REDIRECT: bool = Field(
        default=True, validation_alias=AliasChoices("MITXPRO_SECURE_SSL_REDIRECT")
    )
    SENTRY_DSN: str | None = Field(
        default=None,
        validation_alias=AliasChoices("SENTRY_DSN"),
        description="initialize Sentry before doing anything else so we capture any config errors",  # noqa: E501
    )  # REDACTED: name looks secret-like — set via a source, not here
    SENTRY_LOG_LEVEL: str = Field(
        default="ERROR", validation_alias=AliasChoices("SENTRY_LOG_LEVEL")
    )
    SESSION_ENGINE: str = Field(
        default="django.contrib.sessions.backends.signed_cookies"
    )
    SHEETS_ADMIN_EMAILS: Annotated[list[str], NoDecode] = Field(
        default_factory=lambda: [], validation_alias=AliasChoices("SHEETS_ADMIN_EMAILS")
    )
    SHEETS_DATE_FORMAT: str = Field(
        default="%m/%d/%Y %H:%M:%S", validation_alias=AliasChoices("SHEETS_DATE_FORMAT")
    )
    SHEETS_DATE_ONLY_FORMAT: str = Field(
        default="%m/%d/%Y", validation_alias=AliasChoices("SHEETS_DATE_ONLY_FORMAT")
    )
    SHEETS_DATE_TIMEZONE: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    SHEETS_DEFERRAL_FIRST_ROW: int = Field(
        default=5, validation_alias=AliasChoices("SHEETS_DEFERRAL_FIRST_ROW")
    )
    SHEETS_MONITORING_FREQUENCY: int = Field(
        default_factory=lambda: 60 * 60 * 2,
        validation_alias=AliasChoices("SHEETS_MONITORING_FREQUENCY"),
    )
    SHEETS_REFUND_COMPLETED_DATE_COL: int = Field(
        default=12, validation_alias=AliasChoices("SHEETS_REFUND_COMPLETED_DATE_COL")
    )
    SHEETS_REFUND_ERROR_COL: int = Field(
        default=13, validation_alias=AliasChoices("SHEETS_REFUND_ERROR_COL")
    )
    SHEETS_REFUND_FIRST_ROW: int = Field(
        default=4, validation_alias=AliasChoices("SHEETS_REFUND_FIRST_ROW")
    )
    SHEETS_REFUND_PROCESSOR_COL: int = Field(
        default=11, validation_alias=AliasChoices("SHEETS_REFUND_PROCESSOR_COL")
    )
    SHEETS_REFUND_SKIP_ROW_COL: int = Field(
        default=14, validation_alias=AliasChoices("SHEETS_REFUND_SKIP_ROW_COL")
    )
    SHEETS_REQ_CALCULATED_COLUMNS: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    SHEETS_REQ_EMAIL_COL: int = Field(
        default=7,
        description="Specify the zero-based index of certain request sheet columns",
    )
    SHEETS_REQ_ERROR_COL: int = Field(default=9)
    SHEETS_REQ_ERROR_COL_LETTER: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    SHEETS_REQ_PROCESSED_COL: int = Field(default=8)
    SHEETS_REQ_PROCESSED_COL_LETTER: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    SHEETS_TASK_OFFSET: int = Field(
        default_factory=lambda: 60 * 5,
        validation_alias=AliasChoices("SHEETS_TASK_OFFSET"),
    )
    SILKY_ANALYZE_QUERIES: bool = Field(default=True)
    SITE_BASE_URL: str = Field(..., validation_alias=AliasChoices("MITXPRO_BASE_URL"))
    SITE_ID: str = Field(default=1, validation_alias=AliasChoices("MITXPRO_SITE_ID"))
    SITE_NAME: str = Field(
        default="MIT xPRO", validation_alias=AliasChoices("SITE_NAME")
    )
    SOCIAL_AUTH_ALLOWED_REDIRECT_HOSTS: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    SOCIAL_AUTH_EMAIL_FORCE_EMAIL_VALIDATION: bool = Field(
        default=True, description="Only validate emails for the email backend"
    )
    SOCIAL_AUTH_EMAIL_FORM_HTML: str = Field(default="login.html")
    SOCIAL_AUTH_EMAIL_FORM_URL: str = Field(
        default="login", description="Email backend settings"
    )
    SOCIAL_AUTH_EMAIL_USER_FIELDS: Annotated[list[Any], NoDecode] = Field(
        default_factory=lambda: ["username", "email", "name", "password"]
    )
    SOCIAL_AUTH_EMAIL_VALIDATION_FUNCTION: str = Field(
        default="mail.verification_api.send_verification_email",
        description="Configure social_core.pipeline.mail.mail_validation",
    )
    SOCIAL_AUTH_EMAIL_VALIDATION_URL: str = Field(default="/")
    SOCIAL_AUTH_LOGIN_ERROR_URL: str = Field(default="login")
    SOCIAL_AUTH_PIPELINE: tuple[Any, ...] = Field(
        default=(
            "authentication.pipeline.user.forbid_hijack",
            "social_core.pipeline.social_auth.social_details",
            "social_core.pipeline.social_auth.social_uid",
            "social_core.pipeline.social_auth.auth_allowed",
            "social_core.pipeline.social_auth.social_user",
            "social_core.pipeline.social_auth.associate_by_email",
            "authentication.pipeline.user.validate_email_auth_request",
            "authentication.pipeline.user.validate_email",
            "authentication.pipeline.user.validate_password",
            "social_core.pipeline.mail.mail_validation",
            "authentication.pipeline.user.send_user_to_hubspot",
            "authentication.pipeline.user.get_username",
            "authentication.pipeline.user.create_user_via_email",
            "authentication.pipeline.compliance.verify_exports_compliance",
            "social_core.pipeline.social_auth.associate_user",
            "authentication.pipeline.user.activate_user",
            "authentication.pipeline.user.create_courseware_user",
            "authentication.pipeline.user.create_profile",
            "social_core.pipeline.social_auth.load_extra_data",
            "social_core.pipeline.user.user_details",
            "authentication.pipeline.user.sync_user_to_hubspot",
        ),
    )  # TODO: refine type
    STATICFILES_DIRS: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    STATICFILES_FINDERS: Annotated[list[Any], NoDecode] = Field(
        default_factory=lambda: [
            "django.contrib.staticfiles.finders.FileSystemFinder",
            "django.contrib.staticfiles.finders.AppDirectoriesFinder",
        ],
    )
    STATIC_ROOT: str = Field(default="staticfiles")
    STATIC_URL: str = Field(
        default="/static/", description="Serve static files with dj-static"
    )
    STORAGES: Annotated[dict[str, Any], NoDecode] = Field(
        default_factory=lambda: {
            "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
            "staticfiles": {
                "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"
            },
        },
    )
    TEMPLATES: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    TIME_ZONE: str = Field(default="UTC")
    USE_CELERY: bool = Field(default=True, description="Celery")
    USE_I18N: bool = Field(default=True)
    USE_TZ: bool = Field(default=True)
    USE_X_FORWARDED_HOST: bool = Field(
        default=False, validation_alias=AliasChoices("USE_X_FORWARDED_HOST")
    )
    VERSION: str = Field(default="0.195.2")
    VOUCHER_COMPANY_ID: int = Field(
        default="1", validation_alias=AliasChoices("VOUCHER_COMPANY_ID")
    )
    VOUCHER_DOMESTIC_AMOUNT_KEY: str = Field(
        default="UNIQUE08", validation_alias=AliasChoices("VOUCHER_DOMESTIC_AMOUNT_KEY")
    )
    VOUCHER_DOMESTIC_COURSE_KEY: str = Field(
        default="UNIQUE05", validation_alias=AliasChoices("VOUCHER_DOMESTIC_COURSE_KEY")
    )
    VOUCHER_DOMESTIC_CREDITS_KEY: str = Field(
        default="UNIQUE06",
        validation_alias=AliasChoices("VOUCHER_DOMESTIC_CREDITS_KEY"),
    )
    VOUCHER_DOMESTIC_DATES_KEY: str = Field(
        default="UNIQUE07", validation_alias=AliasChoices("VOUCHER_DOMESTIC_DATES_KEY")
    )
    VOUCHER_DOMESTIC_EMPLOYEE_ID_KEY: str = Field(
        default="UNIQUE03",
        validation_alias=AliasChoices("VOUCHER_DOMESTIC_EMPLOYEE_ID_KEY"),
    )
    VOUCHER_DOMESTIC_EMPLOYEE_KEY: str = Field(
        default="UNIQUE02",
        validation_alias=AliasChoices("VOUCHER_DOMESTIC_EMPLOYEE_KEY"),
        description="Voucher keys for PDF parsing",
    )
    VOUCHER_DOMESTIC_KEY: str = Field(
        default="UNIQUE04", validation_alias=AliasChoices("VOUCHER_DOMESTIC_KEY")
    )
    VOUCHER_INTERNATIONAL_COURSE_NAME_KEY: str = Field(
        default="UNIQUE16",
        validation_alias=AliasChoices("VOUCHER_INTERNATIONAL_COURSE_NAME_KEY"),
    )
    VOUCHER_INTERNATIONAL_COURSE_NUMBER_KEY: str = Field(
        default="UNIQUE17",
        validation_alias=AliasChoices("VOUCHER_INTERNATIONAL_COURSE_NUMBER_KEY"),
    )
    VOUCHER_INTERNATIONAL_DATES_KEY: str = Field(
        default="UNIQUE15",
        validation_alias=AliasChoices("VOUCHER_INTERNATIONAL_DATES_KEY"),
    )
    VOUCHER_INTERNATIONAL_EMPLOYEE_ID_KEY: str = Field(
        default="UNIQUE13",
        validation_alias=AliasChoices("VOUCHER_INTERNATIONAL_EMPLOYEE_ID_KEY"),
    )
    VOUCHER_INTERNATIONAL_EMPLOYEE_KEY: str = Field(
        default="UNIQUE09",
        validation_alias=AliasChoices("VOUCHER_INTERNATIONAL_EMPLOYEE_KEY"),
    )
    WAGTAILADMIN_BASE_URL: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    WAGTAILEMBEDS_FINDERS: Annotated[list[Any], NoDecode] = Field(
        default_factory=lambda: [
            {"class": "cms.embeds.YouTubeEmbedFinder"},
            {"class": "wagtail.embeds.finders.oembed"},
        ],
    )
    WAGTAIL_CACHE_BACKEND: str = Field(
        default="django_redis.cache.RedisCache",
        validation_alias=AliasChoices("WAGTAIL_CACHE_BACKEND"),
        description="Wagtail",
    )
    WAGTAIL_CACHE_MAX_ENTRIES: int = Field(
        default=200, validation_alias=AliasChoices("WAGTAIL_CACHE_MAX_ENTRIES")
    )
    WAGTAIL_CACHE_URL: str | None = Field(
        default=None, validation_alias=AliasChoices("WAGTAIL_CACHE_URL")
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    WAGTAIL_SITE_NAME: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    WEBPACK_LOADER: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    WSGI_APPLICATION: str = Field(default="mitxpro.wsgi.application")
    # <<< aqueduct:generated:fields

    # >>> aqueduct:generated:container_decoders
    @field_validator(
        "ALLOWED_HOSTS",
        "CELERY_ACCEPT_CONTENT",
        "CSRF_TRUSTED_ORIGINS",
        "DIGITAL_CREDENTIALS_SUPPORTED_RUNS",
        "EXTERNAL_COURSE_SYNC_EMAIL_RECIPIENTS",
        "MITOL_MAIL_MESSAGE_CLASSES",
        "SHEETS_ADMIN_EMAILS",
        "SOCIAL_AUTH_EMAIL_USER_FIELDS",
        "STATICFILES_FINDERS",
        "WAGTAILEMBEDS_FINDERS",
        mode="before",
    )
    @classmethod
    def _aqueduct_decode_list_fields(cls, value: object) -> object:
        """Parse a list from a JSON, Python-literal, or comma-separated env string."""
        if not isinstance(value, str):
            return value
        try:
            parsed = json.loads(value)
        except (ValueError, TypeError):
            try:
                parsed = ast.literal_eval(value)
            except (ValueError, SyntaxError):
                parsed = None
        if isinstance(parsed, list):
            return parsed
        stripped = value.strip()
        if stripped.startswith("[") and stripped.endswith("]"):
            stripped = stripped[1:-1].strip()
        if not stripped:
            return []
        return [item.strip() for item in stripped.split(",")]

    @field_validator("REST_FRAMEWORK", "STORAGES", mode="before")
    @classmethod
    def _aqueduct_decode_dict_fields(cls, value: object) -> object:
        """Parse a dict from a JSON or Python-literal env string."""
        if not isinstance(value, str):
            return value
        try:
            parsed = json.loads(value)
        except (ValueError, TypeError):
            parsed = None
        if isinstance(parsed, dict):
            return parsed
        return ast.literal_eval(value)

    # <<< aqueduct:generated:container_decoders

    # >>> aqueduct:preserved:validators
    # -----------------------------------------------------------------
    # Hand-maintained refinements. A field declared here overrides the
    # generated declaration above (last definition wins in a class body)
    # and survives regeneration; see docs/aqueduct.md for the workflow.
    # -----------------------------------------------------------------

    # --- Env inputs the legacy module reads inline (they never become
    # Django settings there; listed in [tool.aqueduct] parity_ignore) ---
    # default_factory (not default=f"...") so BASE_DIR resolves to the module
    # global at call time; in class-body scope it would shadow-resolve to the
    # generated ``BASE_DIR`` FieldInfo above.
    DATABASE_URL: str = Field(
        default_factory=lambda: f"sqlite:///{BASE_DIR}/db.sqlite3",
        description="The connection url to the Postgres database",
    )
    MITXPRO_DB_CONN_MAX_AGE: int = Field(
        default=0, description="Maximum age of connection to Postgres in seconds"
    )
    MITXPRO_DB_DISABLE_SS_CURSORS: bool = Field(
        default=True, description="Disables Postgres server side cursors"
    )
    MITXPRO_DB_DISABLE_SSL: bool = Field(
        default=False, description="Disables SSL to postgres if set to True"
    )
    HOST_IP: str = Field(default="127.0.0.1", description="This server's host IP")
    REDIS_URL: str | None = Field(
        default=None, description="Redis URL for non-production use"
    )
    HUBSPOT_NEW_COURSES_FORM_GUID: str = Field(
        default="",
        description="Form guid over hub spot for new courses email subscription form.",
    )
    HUBSPOT_FOOTER_FORM_GUID: str = Field(
        default="", description="Form guid over hub spot for footer block."
    )
    HUBSPOT_PORTAL_ID: str = Field(default="", description="Hub spot portal id.")
    HUBSPOT_CREATE_USER_FORM_ID: str | None = Field(
        default=None, description="Form ID for Hubspot Forms API"
    )
    HUBSPOT_ENTERPRISE_PAGE_FORM_ID: str | None = Field(
        default=None, description="Form ID for Hubspot for Enterprise Page"
    )
    # Legacy reads this only *inside* the OAUTH2_PROVIDER dict (via
    # get_delimited_list), never as a module-level setting, so static discovery
    # does not generate a field for it — the generated container-decoder does
    # not cover it. Keep the hand-written NoDecode + a dedicated before-validator
    # (`_split_oauth_schemes`) so a comma-separated env value still parses.
    OAUTH2_PROVIDER_ALLOWED_REDIRECT_URI_SCHEMES: Annotated[
        list[str], NoDecode
    ] = Field(
        default_factory=lambda: ["http", "https"],
        description="List of schemes allowed for oauth2 redirect URIs",
    )
    REFRESH_TOKEN_EXPIRE_SECONDS: int = Field(
        default=60 * 60 * 24 * 30,
        description="Number of seconds until a refresh token expires",
    )
    # Raw env value; `_derive_remaining` converts it to a ZoneInfo and stores
    # it on `SHEETS_DATE_TIMEZONE`, like mitxpro/settings.py does.
    SHEETS_DATE_TIMEZONE_NAME: str = Field(
        default="UTC",
        validation_alias="SHEETS_DATE_TIMEZONE",
        description=(
            "The name of the timezone that should be assumed for date/time values "
            "in spreadsheets"
        ),
    )

    # --- Refinements of generated fields -------------------------------
    # The generator redacts secret-shaped names to `default=None` and marks
    # a field required whenever the legacy declaration says required=True.
    # The overrides below restore real (non-secret) legacy defaults, and
    # relax required=True declarations that carry a non-empty default —
    # mitol's `envs.validate()` treats those as satisfied, so making them
    # pydantic-required would reject environments that work today.
    # (`ADMIN_EMAIL`, whose legacy default is "", stays pydantic-required:
    # `envs.validate()` treats an empty string as missing.)
    BASE_DIR: str = Field(default_factory=lambda: BASE_DIR)
    # Generated as `str` (the annotation follows the default expr, not the
    # `get_int` reader); legacy `SITE_ID = MITXPRO_SITE_ID` is an int.
    SITE_ID: int = Field(default=1, validation_alias="MITXPRO_SITE_ID")
    # Generated with a string default `"1"` (the default expr is the literal
    # "1"); legacy `VOUCHER_COMPANY_ID = get_int(...)` is an int. Restore the
    # int default so the field's declared type and its default agree.
    VOUCHER_COMPANY_ID: int = Field(
        default=1, validation_alias="VOUCHER_COMPANY_ID"
    )
    ENVIRONMENT: str = Field(
        default="dev",
        validation_alias="MITXPRO_ENVIRONMENT",
        description="The execution environment that the app is in",
    )
    SENTRY_DSN: str = Field(
        default="", description="The connection settings for Sentry"
    )
    EMAIL_HOST_PASSWORD: str = Field(
        default="",
        validation_alias="MITXPRO_EMAIL_PASSWORD",
        description="Outgoing e-mail auth password",
    )
    POSTHOG_PROJECT_API_KEY: str = Field(default="")
    POSTHOG_PERSONAL_API_KEY: str = Field(default="")
    RECAPTCHA_SECRET_KEY: str = Field(
        default="", description="The ReCaptcha secret key"
    )
    OPENEDX_API_BASE_URL: str = Field(
        default="http://local.openedx.io:8000",
        description="The base URL for the Open edX API",
    )
    OPENEDX_OAUTH_APP_NAME: str = Field(
        default="edx-oauth-app",
        description="The 'name' value for the Open edX OAuth Application",
    )
    OPENEDX_TOKEN_EXPIRES_HOURS: int = Field(
        default=1000,
        description="The number of hours until an access token for the Open edX API expires",
    )
    OAUTH2_PROVIDER_ACCESS_TOKEN_MODEL: str = Field(
        default="oauth2_provider.AccessToken"
    )
    OAUTH2_PROVIDER_REFRESH_TOKEN_MODEL: str = Field(
        default="oauth2_provider.RefreshToken"
    )
    PASSWORD_RESET_CONFIRM_URL: str = Field(
        default="password_reset/confirm/{uid}/{token}/"  # pragma: allowlist secret
    )
    MITOL_DIGITAL_CREDENTIALS_BUILD_CREDENTIAL_FUNC: str = Field(
        default="courses.credentials.build_digital_credential"
    )
    # The generator REDACTS this to `default=None` (name contains
    # "CREDENTIALS"); legacy default is `[]`. Restore the empty-list default.
    # Comma/JSON env decoding is handled by the generated
    # `_aqueduct_decode_list_fields` validator (it lists this field by name).
    DIGITAL_CREDENTIALS_SUPPORTED_RUNS: Annotated[list[str], NoDecode] = Field(
        default_factory=list,
        description="Comma separated string of course/program runs/Ids that support digital credentials",
    )

    # mitol's get_string/get_int with a mixed default: crontab() accepts
    # either, and the legacy defaults are (inconsistently) int 0 / str "0".
    CRON_COURSE_CERTIFICATES_HOURS: int | str = Field(default=0)
    CRON_COURSERUN_SYNC_HOURS: int | str = Field(default=0)
    CRON_EXTERNAL_COURSERUN_SYNC_HOURS: int | str = Field(default="0")
    CRON_BASKET_DELETE_HOURS: int | str = Field(default=0)

    # NOTE: CSRF_TRUSTED_ORIGINS, SHEETS_ADMIN_EMAILS, and
    # EXTERNAL_COURSE_SYNC_EMAIL_RECIPIENTS are no longer overridden here. As of
    # django-aqueduct 0.7.1 the generator emits `Annotated[list[str], NoDecode]`
    # plus a `_aqueduct_decode_list_fields` before-validator (in the
    # aqueduct:generated:container_decoders region) that parses JSON, Python
    # literals, or comma-separated env strings — replacing the hand-written
    # NoDecode + `_split_delimited` workaround these three fields used to carry.
    #
    # NOTE: the ~22-field AnyUrl neutralization block that used to live here is
    # gone too. django-aqueduct 0.9.0 made the `str`→`AnyUrl` promotion opt-in
    # (`[tool.aqueduct] enrich_url_types`, left off here) and denylists the
    # relative-URL Django settings, so the generated `*_URL` fields render as
    # plain `str` again — matching how mitxpro consumes them (urlparse, redis /
    # cache LOCATION, string concat, the PostHog client) and the legacy str
    # values, with no hand overrides needed.

    # --- Typed placeholders for DERIVED fields (populated by the
    # validators below) --------------------------------------------------
    DEFAULT_DATABASE_CONFIG: dict[str, Any] = Field(default_factory=dict)
    DATABASES: dict[str, Any] = Field(default_factory=dict)
    CACHES: dict[str, Any] = Field(default_factory=dict)
    ADMINS: tuple[tuple[str, str], ...] = Field(default_factory=tuple)
    ANYMAIL: dict[str, Any] = Field(default_factory=dict)
    OAUTH2_PROVIDER: dict[str, Any] = Field(default_factory=dict)
    HUBSPOT_CONFIG: dict[str, Any] = Field(default_factory=dict)
    FEATURES: dict[str, Any] = Field(default_factory=dict)
    CELERY_BEAT_SCHEDULE: dict[str, Any] = Field(default_factory=dict)
    INSTALLED_APPS: tuple[str, ...] = Field(default_factory=tuple)
    MIDDLEWARE: tuple[str, ...] = Field(default_factory=tuple)
    INTERNAL_IPS: tuple[str, ...] = Field(default_factory=tuple)
    STATICFILES_DIRS: tuple[str, ...] = Field(
        default_factory=lambda: (f"{BASE_DIR}/static",)
    )
    WEBPACK_LOADER: dict[str, Any] = Field(default_factory=dict)
    STORAGES: dict[str, Any] = Field(default_factory=dict)
    AWS_S3_CUSTOM_DOMAIN: str | None = Field(default=None)
    SOCIAL_AUTH_ALLOWED_REDIRECT_HOSTS: list[str] = Field(default_factory=list)
    WAGTAILADMIN_BASE_URL: str = Field(default="")
    WAGTAIL_SITE_NAME: str = Field(default="")
    MITOL_AUTHENTICATION_FROM_EMAIL: str = Field(default="")
    MITOL_AUTHENTICATION_REPLY_TO_EMAIL: str = Field(default="")
    MITOL_MAIL_FROM_EMAIL: str = Field(default="")
    MITOL_MAIL_REPLY_TO_ADDRESS: str = Field(default="")
    MITOL_MAIL_RECIPIENT_OVERRIDE: str | None = Field(default=None)
    EMAIL_SUPPORT: str | None = Field(
        default=None,
        validation_alias="MITXPRO_SUPPORT_EMAIL",
        description="Email address listed for customer support",
    )
    REPAIR_COURSEWARE_USERS_OFFSET: int = Field(default=0)
    SHEETS_DATE_TIMEZONE: Any = Field(default=None)
    SHEETS_REQ_CALCULATED_COLUMNS: set[int] = Field(default_factory=set)
    SHEETS_REQ_PROCESSED_COL_LETTER: str = Field(default="")
    SHEETS_REQ_ERROR_COL_LETTER: str = Field(default="")
    OPENEDX_BASE_REDIRECT_URL: str | None = Field(
        default=None,
        description="The base redirect URL for an OAuth Application for the Open edX API",
    )
    LOGGING: dict[str, Any] = Field(default_factory=lambda: dict(MITOL_LOGGING))
    DJOSER: dict[str, Any] = Field(
        default_factory=lambda: {
            "PASSWORD_RESET_CONFIRM_URL": "password_reset/confirm/{uid}/{token}/",  # pragma: allowlist secret
            "SET_PASSWORD_RETYPE": False,
            "LOGOUT_ON_PASSWORD_CHANGE": False,
            "PASSWORD_RESET_CONFIRM_RETYPE": True,
            "PASSWORD_RESET_SHOW_EMAIL_NOT_FOUND": False,
            "EMAIL": {
                "password_reset": "mitol.authentication.views.djoser_views.CustomPasswordResetEmail"  # pragma: allowlist secret
            },
            "SERIALIZERS": {
                "password_reset": "mitol.authentication.serializers.djoser_serializers.CustomSendEmailResetSerializer"  # pragma: allowlist secret
            },
        }
    )
    TEMPLATES: list[dict[str, Any]] = Field(
        default_factory=lambda: [
            {
                "BACKEND": "django.template.backends.django.DjangoTemplates",
                "DIRS": [f"{BASE_DIR}/templates"],
                "APP_DIRS": True,
                "OPTIONS": {
                    "context_processors": [
                        "django.template.context_processors.debug",
                        "django.template.context_processors.request",
                        "django.contrib.auth.context_processors.auth",
                        "django.contrib.messages.context_processors.messages",
                        "social_django.context_processors.backends",
                        "social_django.context_processors.login_redirect",
                        "mitxpro.context_processors.api_keys",
                        "mitxpro.context_processors.configuration_context",
                    ]
                },
            }
        ]
    )

    # -----------------------------------------------------------------
    # Validators (run in definition order)
    # -----------------------------------------------------------------

    @field_validator("OAUTH2_PROVIDER_ALLOWED_REDIRECT_URI_SCHEMES", mode="before")
    @classmethod
    def _split_oauth_schemes(cls, value: Any) -> Any:
        """Split a comma-delimited env string for the one non-generated list field.

        Every other list field is covered by the generated
        `_aqueduct_decode_list_fields` validator; this field is not a
        module-level setting in the legacy source, so it has no generated
        counterpart and needs its own split.
        """
        if isinstance(value, str):
            return [item.strip() for item in value.split(",") if item.strip()]
        return value

    @model_validator(mode="after")
    def _resolve_redis_urls(self) -> "AqueductSettings":
        """The `_redis_url` fallback chain in mitxpro/settings.py.

        ``REDISCLOUD_URL`` wins when set; otherwise fall back to
        ``REDIS_URL``. Any of ``CELERY_BROKER_URL``, ``CELERY_RESULT_BACKEND``,
        ``CELERY_REDBEAT_REDIS_URL``, or ``WAGTAIL_CACHE_URL`` that were not
        explicitly set default to this resolved Redis URL.
        """
        redis_url = dv.first_url(self.REDISCLOUD_URL, self.REDIS_URL)
        if self.CELERY_BROKER_URL is None:
            self.CELERY_BROKER_URL = redis_url
        if self.CELERY_RESULT_BACKEND is None:
            self.CELERY_RESULT_BACKEND = redis_url
        if self.CELERY_REDBEAT_REDIS_URL is None:
            self.CELERY_REDBEAT_REDIS_URL = redis_url
        if self.WAGTAIL_CACHE_URL is None:
            self.WAGTAIL_CACHE_URL = redis_url
        return self

    @model_validator(mode="after")
    def _collect_features(self) -> "AqueductSettings":
        """FEATURE_* flags: the legacy env scan plus source-supplied extras.

        ``get_features()`` reproduces `mitol.common.envs.get_features` exactly,
        including raising ``ImproperlyConfigured`` on values that are not
        true/false (the previous hand-written scan silently dropped them).
        Flags supplied by a non-env source (e.g. Vault) arrive as model
        extras and are overlaid via ``derivations.feature_flags``.
        """
        features: dict[str, Any] = get_features()
        features.update(dv.feature_flags(self.model_extra or {}))
        self.FEATURES = features
        return self

    @model_validator(mode="after")
    def _validate_s3_config(self) -> "AqueductSettings":
        """Mirror the S3 cross-field validation in mitxpro/settings.py."""
        if self.MITXPRO_USE_S3 and (
            not self.AWS_ACCESS_KEY_ID
            or not self.AWS_SECRET_ACCESS_KEY
            or not self.AWS_STORAGE_BUCKET_NAME
        ):
            raise ImproperlyConfigured(
                "You have enabled S3 support, but are missing one of "
                "AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, or "
                "AWS_STORAGE_BUCKET_NAME"
            )
        return self

    @model_validator(mode="after")
    def _build_installed_apps_and_middleware(self) -> "AqueductSettings":
        """Reconstruct the ENVIRONMENT/DEBUG-conditional app & middleware lists."""
        installed_apps = (
            "django.contrib.admin",
            "django.contrib.auth",
            "django.contrib.contenttypes",
            "django.contrib.sessions",
            "django.contrib.messages",
            "django.contrib.staticfiles",
            "django.contrib.humanize",
            "django.contrib.sites",
            "django.contrib.sitemaps",
            "django_user_agents",
            "social_django",
            "oauth2_provider",
            "rest_framework",
            "anymail",
            "django_filters",
            # WAGTAIL
            "wagtail.contrib.forms",
            "wagtail.contrib.redirects",
            "wagtail.contrib.table_block",
            "wagtail.contrib.routable_page",
            "wagtail.embeds",
            "wagtail.sites",
            "users.apps.MitxproWagtailUsersAppConfig",
            "wagtail.snippets",
            "wagtail.documents",
            "wagtail.images",
            "wagtail.search",
            "wagtail.admin",
            "wagtail",
            "wagtailmetadata",
            "modelcluster",
            "taggit",
            "wagtail.api.v2",
            # django-robots
            "robots",
            # project apps
            "mitxpro",
            "authentication",
            "courses",
            "mail.apps.MailApp",
            "users",
            "cms",
            "compliance",
            "courseware",
            "sheets",
            "affiliate",
            # must be after "users" to pick up custom user model
            "b2b_ecommerce",
            "ecommerce",
            "hijack",
            "hijack.contrib.admin",
            "hubspot_xpro",
            "voucher",
            "maxmind",
            # ol-django apps, must be after this project's apps for template precedence
            "mitol.hubspot_api.apps.HubspotApiApp",
            "mitol.common.apps.CommonApp",
            "mitol.observability.apps.ObservabilityConfig",
            "mitol.digitalcredentials.apps.DigitalCredentialsApp",
            "mitol.mail.apps.MailApp",
            "mitol.oauth_toolkit_extensions.apps.OAuthToolkitExtensionsApp",
            "mitol.authentication.apps.TransitionalAuthenticationApp",
            "mitol.olposthog.apps.OlPosthog",
            "health_check",
            "django_aqueduct",
        )
        if self.ENVIRONMENT not in ("production", "prod"):
            installed_apps += ("localdev.seed",)
        if not self.WEBPACK_DISABLE_LOADER_STATS:
            installed_apps += ("webpack_loader",)

        middleware = (
            "django.middleware.security.SecurityMiddleware",
            "mitxpro.middleware.HostnameRedirectMiddleware",
            "django.contrib.sessions.middleware.SessionMiddleware",
            "affiliate.middleware.AffiliateMiddleware",
            "oauth2_provider.middleware.OAuth2TokenMiddleware",
            "django.middleware.common.CommonMiddleware",
            "django.middleware.csrf.CsrfViewMiddleware",
            "django.contrib.auth.middleware.AuthenticationMiddleware",
            "hijack.middleware.HijackUserMiddleware",
            "django.contrib.messages.middleware.MessageMiddleware",
            "django.middleware.clickjacking.XFrameOptionsMiddleware",
            "django.contrib.sites.middleware.CurrentSiteMiddleware",
            "django_user_agents.middleware.UserAgentMiddleware",
            "wagtail.contrib.redirects.middleware.RedirectMiddleware",
        )
        if self.DEBUG:
            installed_apps += ("nplusone.ext.django", "silk")
            middleware += (
                "nplusone.ext.django.NPlusOneMiddleware",
                "silk.middleware.SilkyMiddleware",
            )
            installed_apps += ("debug_toolbar",)
            middleware = (
                "debug_toolbar.middleware.DebugToolbarMiddleware",
                *middleware,
            )

        self.INSTALLED_APPS = installed_apps
        self.MIDDLEWARE = middleware
        return self

    @model_validator(mode="after")
    def _build_static_and_storage(self) -> "AqueductSettings":
        """Mirror the CLOUDFRONT_DIST-conditional STATIC_URL/STORAGES logic."""
        static_url = "/static/"
        if self.CLOUDFRONT_DIST:
            static_url = urljoin(
                f"https://{self.CLOUDFRONT_DIST}.cloudfront.net", static_url
            )
        self.STATIC_URL = static_url

        storages: dict[str, Any] = {
            "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
            "staticfiles": {
                "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"
            },
        }
        if self.MITXPRO_USE_S3:
            if self.CLOUDFRONT_DIST:
                self.AWS_S3_CUSTOM_DOMAIN = f"{self.CLOUDFRONT_DIST}.cloudfront.net"
            storages["default"] = {
                "BACKEND": "storages.backends.s3boto3.S3Boto3Storage"
            }
        self.STORAGES = storages
        return self

    @model_validator(mode="after")
    def _build_webpack_loader(self) -> "AqueductSettings":
        self.WEBPACK_LOADER = {
            "DEFAULT": {
                "CACHE": not self.DEBUG,
                "BUNDLE_DIR_NAME": "bundles/",
                "STATS_FILE": f"{self.BASE_DIR}/webpack-stats.json",
                "POLL_INTERVAL": 0.1,
                "TIMEOUT": None,
                "IGNORE": [r".+\.hot-update\.+", r".+\.js\.map"],
            }
        }
        return self

    @model_validator(mode="after")
    def _build_databases(self) -> "AqueductSettings":
        """DATABASES via derivations.database_config.

        Unlike the legacy module, ``database_config`` never applies
        ``sslmode`` to a SQLite URL (SQLite's driver rejects it).
        """
        config = dv.database_config(
            self.DATABASE_URL,
            conn_max_age=self.MITXPRO_DB_CONN_MAX_AGE,
            ssl_require=not self.MITXPRO_DB_DISABLE_SSL,
        )
        config["DISABLE_SERVER_SIDE_CURSORS"] = self.MITXPRO_DB_DISABLE_SS_CURSORS
        config.setdefault("OPTIONS", {})
        self.DEFAULT_DATABASE_CONFIG = config
        self.DATABASES = {"default": config}
        return self

    @model_validator(mode="after")
    def _build_caches(self) -> "AqueductSettings":
        self.CACHES = {
            "default": {
                "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
                "LOCATION": "local-in-memory-cache",
            },
            "redis": dv.redis_cache(
                self.CELERY_BROKER_URL,
                CLIENT_CLASS="django_redis.client.DefaultClient",
            ),
            "renditions": {
                **dv.redis_cache(
                    self.WAGTAIL_CACHE_URL,
                    backend=self.WAGTAIL_CACHE_BACKEND,
                    MAX_ENTRIES=self.WAGTAIL_CACHE_MAX_ENTRIES,
                    CLIENT_CLASS="django_redis.client.DefaultClient",
                ),
                "TIMEOUT": 31_536_000,  # 1 year
                "KEY_PREFIX": "wag",
            },
            "durable": {
                "BACKEND": "django.core.cache.backends.db.DatabaseCache",
                "LOCATION": "durable_cache",
            },
        }
        return self

    @model_validator(mode="after")
    def _build_anymail_admins_and_oauth(self) -> "AqueductSettings":
        self.ANYMAIL = {
            "MAILGUN_API_KEY": self.MAILGUN_KEY,
            "MAILGUN_SENDER_DOMAIN": self.MAILGUN_SENDER_DOMAIN,
        }
        self.ADMINS = (("Admins", self.ADMIN_EMAIL),) if self.ADMIN_EMAIL != "" else ()
        self.SOCIAL_AUTH_ALLOWED_REDIRECT_HOSTS = [
            urlparse(self.SITE_BASE_URL).netloc
        ]
        self.HUBSPOT_CONFIG = {
            "HUBSPOT_NEW_COURSES_FORM_GUID": self.HUBSPOT_NEW_COURSES_FORM_GUID,
            "HUBSPOT_FOOTER_FORM_GUID": self.HUBSPOT_FOOTER_FORM_GUID,
            "HUBSPOT_PORTAL_ID": self.HUBSPOT_PORTAL_ID,
            "HUBSPOT_CREATE_USER_FORM_ID": self.HUBSPOT_CREATE_USER_FORM_ID,
            "HUBSPOT_ENTERPRISE_PAGE_FORM_ID": self.HUBSPOT_ENTERPRISE_PAGE_FORM_ID,
        }
        self.OAUTH2_PROVIDER = {
            # Disable PKCE requirement to maintain backward compatibility with
            # existing OAuth clients (PKCE_REQUIRED changed default to True in
            # django-oauth-toolkit 2.0.0)
            "PKCE_REQUIRED": False,
            "SCOPES": {
                "read": "Read scope",
                "write": "Write scope",
                "user:read": "Can read user and profile data",
                "digitalcredentials": "Can read and write Digital Credentials data",
            },
            "DEFAULT_SCOPES": ["user:read"],
            "SCOPES_BACKEND_CLASS": "mitol.oauth_toolkit_extensions.backends.ApplicationAccessOrSettingsScopes",
            "ERROR_RESPONSE_WITH_SCOPES": self.DEBUG,
            "ALLOWED_REDIRECT_URI_SCHEMES": self.OAUTH2_PROVIDER_ALLOWED_REDIRECT_URI_SCHEMES,
            "REFRESH_TOKEN_EXPIRE_SECONDS": self.REFRESH_TOKEN_EXPIRE_SECONDS,
        }
        return self

    @model_validator(mode="after")
    def _build_celery_beat_schedule(self) -> "AqueductSettings":
        """Rebuild CELERY_BEAT_SCHEDULE, including its crontab/OffsettingSchedule values.

        Must run after `_collect_features` so `FEATURES` is populated.
        """
        self.REPAIR_COURSEWARE_USERS_OFFSET = int(
            self.REPAIR_COURSEWARE_USERS_FREQUENCY / 2
        )

        schedule: dict[str, Any] = {
            "retry-failed-edx-enrollments": {
                "task": "courseware.tasks.retry_failed_edx_enrollments",
                "schedule": self.RETRY_FAILED_EDX_ENROLLMENT_FREQUENCY,
            },
            "repair-faulty-edx-users": {
                "task": "courseware.tasks.repair_faulty_courseware_users",
                "schedule": OffsettingSchedule(
                    run_every=timedelta(seconds=self.REPAIR_COURSEWARE_USERS_FREQUENCY),
                    offset=timedelta(seconds=self.REPAIR_COURSEWARE_USERS_OFFSET),
                ),
            },
            "generate-course-certificate": {
                "task": "courses.tasks.generate_course_certificates",
                "schedule": crontab(
                    minute=0,
                    hour=self.CRON_COURSE_CERTIFICATES_HOURS,
                    day_of_week=self.CRON_COURSE_CERTIFICATES_DAYS or "*",
                    day_of_month="*",
                    month_of_year="*",
                ),
            },
            "sync-courseruns-data": {
                "task": "courses.tasks.sync_courseruns_data",
                "schedule": crontab(
                    minute=0,
                    hour=self.CRON_COURSERUN_SYNC_HOURS,
                    day_of_week=self.CRON_COURSERUN_SYNC_DAYS or "*",
                    day_of_month="*",
                    month_of_year="*",
                ),
            },
            "sync-external-course-runs": {
                "task": "courses.tasks.task_sync_external_course_runs",
                "schedule": crontab(
                    minute="0",
                    hour=self.CRON_EXTERNAL_COURSERUN_SYNC_HOURS,
                    day_of_week=self.CRON_EXTERNAL_COURSERUN_SYNC_DAYS or "*",
                    day_of_month="*",
                    month_of_year="*",
                ),
            },
            "delete-expired-baskets": {
                "task": "ecommerce.tasks.delete_expired_baskets",
                "schedule": crontab(
                    minute=0,
                    hour=self.CRON_BASKET_DELETE_HOURS,
                    day_of_week=self.CRON_BASKET_DELETE_DAYS,
                    day_of_month="*",
                    month_of_year="*",
                ),
            },
            "renew_all_file_watches": {
                "task": "sheets.tasks.renew_all_file_watches",
                "schedule": (
                    self.DRIVE_WEBHOOK_EXPIRATION_MINUTES
                    - self.DRIVE_WEBHOOK_RENEWAL_PERIOD_MINUTES
                )
                * 60,
            },
            "clear-expired-tokens": {
                "task": "mitxpro.tasks.clear_expired_tokens",
                "schedule": crontab(minute=0, hour=9, day_of_week=1),
            },
        }

        alt_sheets_processing = self.FEATURES.get("COUPON_SHEETS_ALT_PROCESSING")
        if alt_sheets_processing:
            schedule["handle-coupon-request-sheet"] = {
                "task": "sheets.tasks.handle_unprocessed_coupon_requests",
                "schedule": self.SHEETS_MONITORING_FREQUENCY,
            }

        schedule["update-assignment-delivery-dates"] = {
            "task": "sheets.tasks.update_incomplete_assignment_delivery_statuses",
            "schedule": OffsettingSchedule(
                run_every=timedelta(seconds=self.SHEETS_MONITORING_FREQUENCY),
                offset=timedelta(
                    seconds=0 if not alt_sheets_processing else self.SHEETS_TASK_OFFSET
                ),
            ),
        }

        self.CELERY_BEAT_SCHEDULE = schedule
        return self

    @model_validator(mode="after")
    def _derive_remaining(self) -> "AqueductSettings":
        """Settings mitxpro/settings.py derives from other settings."""
        self.INTERNAL_IPS = (self.HOST_IP,)
        self.EMAIL_SUPPORT = (
            self.EMAIL_SUPPORT
            if self.EMAIL_SUPPORT is not None
            else (self.MAILGUN_RECIPIENT_OVERRIDE or "support@localhost")
        )

        self.WAGTAILADMIN_BASE_URL = self.SITE_BASE_URL
        self.WAGTAIL_SITE_NAME = self.SITE_NAME

        # mitxpro/settings.py fully overrides the djoser-sourced
        # MITOL_AUTHENTICATION_FROM_EMAIL with MAILGUN_FROM_EMAIL, and
        # introduces MITOL_AUTHENTICATION_REPLY_TO_EMAIL alongside the
        # pre-existing MITOL_AUTHENTICATION_REPLY_TO_ADDRESS.
        self.MITOL_AUTHENTICATION_FROM_EMAIL = self.MAILGUN_FROM_EMAIL
        self.MITOL_AUTHENTICATION_REPLY_TO_EMAIL = self.MITXPRO_REPLY_TO_ADDRESS

        self.MITOL_MAIL_FROM_EMAIL = self.MAILGUN_FROM_EMAIL
        self.MITOL_MAIL_REPLY_TO_ADDRESS = self.MITXPRO_REPLY_TO_ADDRESS
        self.MITOL_MAIL_RECIPIENT_OVERRIDE = self.MAILGUN_RECIPIENT_OVERRIDE

        self.OPENEDX_BASE_REDIRECT_URL = (
            self.OPENEDX_BASE_REDIRECT_URL or self.OPENEDX_API_BASE_URL
        )

        self.SHEETS_DATE_TIMEZONE = ZoneInfo(self.SHEETS_DATE_TIMEZONE_NAME)

        uppercase_a_ord = ord("A")
        self.SHEETS_REQ_CALCULATED_COLUMNS = {
            self.SHEETS_REQ_EMAIL_COL,
            self.SHEETS_REQ_PROCESSED_COL,
            self.SHEETS_REQ_ERROR_COL,
        }
        self.SHEETS_REQ_PROCESSED_COL_LETTER = chr(
            self.SHEETS_REQ_PROCESSED_COL + uppercase_a_ord
        )
        self.SHEETS_REQ_ERROR_COL_LETTER = chr(
            self.SHEETS_REQ_ERROR_COL + uppercase_a_ord
        )
        return self
    # <<< aqueduct:preserved:validators


class DevAqueductSettings(AqueductSettings):
    """Local-dev variant that layers a Vault source over the environment.

    mitxpro's Vault mount is ``secret-xpro``, which still runs the KV **v1**
    secrets engine — the reason a Vault-backed dev settings class was
    deferred until django-aqueduct grew ``kv_version`` support. The source is
    configured entirely from ``VAULT_*`` environment variables (see
    ``django_aqueduct.sources.dev``), with mitxpro-appropriate defaults for
    the mount and KV version:

    * ``VAULT_ADDR`` — required to enable Vault; unset means "run without
      Vault" (plain env/.env dev, identical to ``AqueductSettings``).
    * ``VAULT_PATH`` — the secret path under the mount (required when
      ``VAULT_ADDR`` is set; no repo-discoverable default exists).
    * ``VAULT_MOUNT`` — defaults to ``secret-xpro``.
    * ``VAULT_KV_VERSION`` — defaults to ``1`` (the mount's engine version).
    * ``VAULT_AUTH_METHOD`` / ``VAULT_TOKEN`` / ``VAULT_ROLE`` — auth wiring;
      ``oidc`` + ``VAULT_ROLE`` is the interactive local-dev path.

    Select it via ``DJANGO_SETTINGS_MODULE=mitxpro.settings_aqueduct_dev``.
    """

    @classmethod
    def settings_customise_sources(
        cls,
        settings_cls: type[BaseSettings],
        init_settings: PydanticBaseSettingsSource,
        env_settings: PydanticBaseSettingsSource,
        dotenv_settings: PydanticBaseSettingsSource,
        file_secret_settings: PydanticBaseSettingsSource,
    ) -> tuple[PydanticBaseSettingsSource, ...]:
        """Prepend an env-configured Vault source when VAULT_ADDR is set."""
        base = (
            init_settings,
            env_settings,
            dotenv_settings,
            file_secret_settings,
        )
        env = dict(os.environ)
        env.setdefault("VAULT_MOUNT", "secret-xpro")
        env.setdefault("VAULT_KV_VERSION", "1")
        vault = vault_source_from_env(settings_cls, env)
        return (vault, *base) if vault is not None else base
