# Generated by Django 2.1.7 on 2019-03-05 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("position_in_program", models.PositiveSmallIntegerField(null=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("thumbnail", models.ImageField(blank=True, null=True, upload_to="")),
                ("readable_id", models.CharField(max_length=255, null=True)),
                ("live", models.BooleanField(default=False)),
            ],
            options={"ordering": ("program", "title")},
        ),
        migrations.CreateModel(
            name="CourseRun",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "courseware_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("courseware_url", models.URLField(null=True)),
                ("start_date", models.DateTimeField(db_index=True, null=True)),
                ("end_date", models.DateTimeField(db_index=True, null=True)),
                ("enrollment_start", models.DateTimeField(db_index=True, null=True)),
                ("enrollment_end", models.DateTimeField(db_index=True, null=True)),
                ("live", models.BooleanField(default=False)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="courses.Course"
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("thumbnail", models.ImageField(blank=True, null=True, upload_to="")),
                ("readable_id", models.CharField(max_length=255, null=True)),
                ("live", models.BooleanField(default=False)),
            ],
            options={"abstract": False},
        ),
        migrations.AddField(
            model_name="course",
            name="program",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.Program",
            ),
        ),
    ]
