# Generated by Django 2.1.7 on 2019-03-01 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('courses', '0001_initial'), ('courses', '0002_change_blank_defaults'), ('courses', '0003_nullable_pos_in_program'), ('courses', '0004_nullable_course_program')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_in_program', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
                ('readable_id', models.CharField(max_length=255)),
                ('live', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('edx.org', 'edx.org'), ('Open edX', 'Open edX')], max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('courseware_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('courseware_url', models.URLField(null=True)),
                ('start_date', models.DateTimeField(db_index=True, null=True)),
                ('end_date', models.DateTimeField(db_index=True, null=True)),
                ('enrollment_start', models.DateTimeField(db_index=True, null=True)),
                ('enrollment_end', models.DateTimeField(db_index=True, null=True)),
                ('live', models.BooleanField(default=False)),
                ('platform', models.CharField(choices=[('edx.org', 'edx.org'), ('Open edX', 'Open edX')], max_length=15, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
                ('readable_id', models.CharField(max_length=255, null=True)),
                ('live', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('edx.org', 'edx.org'), ('Open edX', 'Open edX')], max_length=15, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Program'),
        ),
        migrations.AlterField(
            model_name='course',
            name='readable_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='position_in_program',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
