# Generated by Django 2.1.7 on 2019-03-13 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("courses", "0002_course_run_date_blanks")]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="position_in_program",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.Program",
            ),
        ),
    ]
