# Generated by Django 2.1.7 on 2019-03-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("courses", "0003_course_program_defaults")]

    operations = [
        migrations.RemoveField(model_name="courserun", name="courseware_url"),
        migrations.AddField(
            model_name="courserun",
            name="courseware_url_path",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
