# Generated by Django 2.1.7 on 2019-04-03 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("courses", "0004_change_courseware_url_field")]

    operations = [
        migrations.RemoveField(model_name="course", name="description"),
        migrations.RemoveField(model_name="course", name="thumbnail"),
        migrations.RemoveField(model_name="program", name="description"),
        migrations.RemoveField(model_name="program", name="thumbnail"),
    ]
