# Generated by Django 2.1.7 on 2019-05-15 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0010_remove_ecommerce_course_run_enrollment"),
        ("courses", "0007_add_enrollment_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="courserunenrollment",
            name="company",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="ecommerce.Company",
            ),
        ),
        migrations.AddField(
            model_name="programenrollment",
            name="company",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="ecommerce.Company",
            ),
        ),
    ]
