# Generated by Django 2.1.7 on 2019-05-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("courses", "0008_enrollment_company")]

    operations = [
        migrations.AddField(
            model_name="courserunenrollment",
            name="active",
            field=models.BooleanField(
                default=True,
                help_text="Indicates whether or not this enrollment should be considered active",
            ),
        ),
        migrations.AddField(
            model_name="courserunenrollment",
            name="edx_enrolled",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether or not the request succeeded to enroll via the edX API",
            ),
        ),
        migrations.AddField(
            model_name="programenrollment",
            name="active",
            field=models.BooleanField(
                default=True,
                help_text="Indicates whether or not this enrollment should be considered active",
            ),
        ),
    ]
