# Generated by Django 2.1.7 on 2019-06-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("courses", "0010_enrollment_audit_tables")]

    operations = [
        migrations.AddField(
            model_name="courserunenrollment",
            name="change_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("deferred", "deferred"),
                    ("transferred", "transferred"),
                    ("refunded", "refunded"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="programenrollment",
            name="change_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("deferred", "deferred"),
                    ("transferred", "transferred"),
                    ("refunded", "refunded"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
