# Generated by Django 2.1.7 on 2019-06-18 19:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("courses", "0012_backpopulate_readable_id")]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="readable_id",
            field=models.CharField(
                max_length=255,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[\\w\\-+:]+$",
                        "This field is used to produce URL paths. It must contain only characters that match this pattern: [\\w\\-+:]",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="readable_id",
            field=models.CharField(
                max_length=255,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[\\w\\-+:]+$",
                        "This field is used to produce URL paths. It must contain only characters that match this pattern: [\\w\\-+:]",
                    )
                ],
            ),
        ),
    ]
