# Generated by Django 2.1.7 on 2019-06-18 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("courses", "0013_readable_id_required")]

    operations = [
        migrations.AlterField(
            model_name="courserunenrollment",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="ecommerce.Company",
            ),
        ),
        migrations.AlterField(
            model_name="programenrollment",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="ecommerce.Company",
            ),
        ),
    ]
