# Generated by Django 2.1.7 on 2019-06-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("courses", "0014_enrollment_blankable")]

    operations = [
        migrations.AlterField(
            model_name="courserun",
            name="courseware_id",
            field=models.CharField(max_length=255, unique=True),
        )
    ]
