# Generated by Django 2.2.3 on 2019-08-06 10:14

from datetime import timedelta

from django.db import migrations
from django.db.models import F


def backpopulate_expiration_date(apps, schema_editor):
    """
    Fetch all CourseRuns with an end_date and without an expiration_date and set that field
    to end_date + 90 days.
    """
    CourseRun = apps.get_model("courses", "CourseRun")
    CourseRun.objects.filter(
        end_date__isnull=False, expiration_date__isnull=True
    ).update(expiration_date=F("end_date") + timedelta(days=90))


class Migration(migrations.Migration):

    dependencies = [("courses", "0017_courserun_expiration_date")]

    operations = [
        migrations.RunPython(backpopulate_expiration_date, migrations.RunPython.noop)
    ]
