# Generated by Django 2.2.4 on 2019-10-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("courses", "0021_courserungrade_set_by_admin")]

    operations = [
        migrations.CreateModel(
            name="CourseTopic",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128, unique=True)),
            ],
            options={"abstract": False},
        ),
        migrations.AddField(
            model_name="course",
            name="topics",
            field=models.ManyToManyField(blank=True, to="courses.CourseTopic"),
        ),
    ]
