# Generated by Django 2.2.8 on 2020-02-07 18:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("courses", "0023_revoke_certificate")]

    operations = [
        migrations.CreateModel(
            name="ProgramRun",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "run_suffix",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[\\w\\-+:]+$",
                                "This field is used to produce URL paths. It must contain only characters that match this pattern: [\\w\\-+:]",
                            )
                        ],
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "end_date",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programruns",
                        to="courses.Program",
                    ),
                ),
            ],
            options={"unique_together": {("program", "run_suffix")}},
        )
    ]
