# Generated by Django 2.2.8 on 2020-01-06 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("courses", "0023_revoke_certificate")]

    operations = [
        migrations.CreateModel(
            name="ProgramRun",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("run_id", models.CharField(max_length=255)),
                ("live", models.BooleanField(default=False)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programruns",
                        to="courses.Program",
                    ),
                ),
            ],
            options={"unique_together": {("program", "run_id")}},
        ),
        migrations.AddField(
            model_name="courserun",
            name="program_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courseruns",
                to="courses.ProgramRun",
            ),
        ),
    ]
