# Generated by Django 2.2.10 on 2020-02-27 14:37

from django.db import migrations, models


def nullify_courserun_expiration_dates(apps, schema_editor):
    """
    Unset all of the expiration dates set automatically by the previous code.
    We are moving to empty expiration dates by default and only explicitly setting them
    if needed on a specific course run.
    """
    CourseRun = apps.get_model("courses", "CourseRun")
    CourseRun.objects.update(expiration_date=None)


class Migration(migrations.Migration):

    dependencies = [("courses", "0025_run_tag")]

    operations = [
        migrations.AlterField(
            model_name="courserun",
            name="expiration_date",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="The date beyond which the learner should not see link to this course run on their dashboard.",
                null=True,
            ),
        ),
        migrations.RunPython(
            nullify_courserun_expiration_dates, migrations.RunPython.noop
        ),
    ]
