# Generated by Django 3.2.17 on 2023-02-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0029_revert_certificates_prior_aug_8"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="is_external",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="program",
            name="is_external",
            field=models.BooleanField(default=False),
        ),
    ]
