# Generated by Django 3.2.18 on 2023-03-24 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0030_add_courseware_external_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursetopic",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subtopics",
                to="courses.coursetopic",
            ),
        ),
    ]
