# Generated by Django 3.2.18 on 2023-05-04 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0031_create_topics_sublevel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="courserun",
            name="external_marketing_url",
        ),
        migrations.RemoveField(
            model_name="programrun",
            name="external_marketing_url",
        ),
    ]
