# Generated by Django 3.2.20 on 2023-08-10 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0062_comment_models_and_pagesubscription"),
        ("courses", "0033_remove_course_coursetopic_association"),
    ]

    run_before = [
        ("wagtailcore", "0067_alter_pagerevision_content_json"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseruncertificate",
            name="certificate_page_revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="wagtailcore.pagerevision",
            ),
        ),
        migrations.AlterField(
            model_name="programcertificate",
            name="certificate_page_revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="wagtailcore.pagerevision",
            ),
        ),
    ]
