# Generated by Django 3.2.21 on 2023-10-05 23:44

from django.db import migrations, models
import django.db.models.deletion


DEFAULT_PLATFORM_NAME = "xPRO"


def setup_course_platform(apps, schema_editor):
    """Associate a platform to all the courses without a platform"""

    Platform = apps.get_model("courses", "Platform")
    Course = apps.get_model("courses", "Course")

    default_platform, _ = Platform.objects.get_or_create(name=DEFAULT_PLATFORM_NAME)
    courses_without_platform = Course.objects.filter(platform__isnull=True)
    for course in courses_without_platform:
        course.platform = default_platform

    Course.objects.bulk_update(courses_without_platform, ["platform"])


def setup_program_platform(apps, schema_editor):
    """Associate a platform to all the programs without a platform"""

    Platform = apps.get_model("courses", "Platform")
    Program = apps.get_model("courses", "Program")

    default_platform, _ = Platform.objects.get_or_create(name=DEFAULT_PLATFORM_NAME)
    programs_without_platform = Program.objects.filter(platform__isnull=True)
    for program in programs_without_platform:
        program.platform = default_platform

    Program.objects.bulk_update(programs_without_platform, ["platform"])


def populate_platform(apps, schema_editor):
    """Associate courses and programs to a platform if they do not have one"""
    setup_course_platform(apps, schema_editor)
    setup_program_platform(apps, schema_editor)


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0036_add_platform_model"),
    ]

    operations = [
        # Populate all the existing coruses and programs with a plarform before we make the field required.
        migrations.RunPython(populate_platform, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="course",
            name="platform",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="courses.platform"
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="platform",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="courses.platform"
            ),
        ),
    ]
