# Generated by Django 4.2.13 on 2024-06-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0038_alter_certificate_page_revision"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="external_course_id",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="courserun",
            name="external_course_run_id",
            field=models.CharField(default="", max_length=255),
        ),
    ]
