# Generated by Django 4.2.13 on 2024-06-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0038_alter_certificate_page_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='external_course_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='courserun',
            name='external_course_run_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
