# Generated by Django 4.2.17 on 2025-01-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0041_platform_sync_daily"),
    ]

    operations = [
        migrations.RenameField(
            model_name="platform",
            old_name="sync_daily",
            new_name="enable_sync",
        ),
        migrations.AlterField(
            model_name="platform",
            name="enable_sync",
            field=models.BooleanField(
                default=False,
                help_text="Select this option to enable course sync for external platforms.",
            ),
        ),
    ]
