# Generated by Django 4.2.17 on 2025-01-01 14:11

from django.db import migrations, models


def add_default_supported_languages(apps, schema_editor):
    """Add the languages that xPRO platform will support as default"""
    CourseLanguage = apps.get_model("courses.CourseLanguage")
    CourseLanguage.objects.bulk_create(
        [
            CourseLanguage(name="English"),
            CourseLanguage(name="Spanish"),
            CourseLanguage(name="Portuguese"),
            CourseLanguage(name="Mandarin"),
            CourseLanguage(name="Italian"),
            CourseLanguage(name="French"),
        ]
    )


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0041_platform_sync_daily"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseLanguage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunPython(add_default_supported_languages),
    ]
