# Generated by Django 4.2.18 on 2025-01-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0043_rename_sync_daily_platform_enable_sync"),
    ]

    operations = [
        migrations.AddField(
            model_name="courselanguage",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
