# Generated by Django 3.2.15 on 2022-10-13 20:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hubspot_xpro", "0002_hubspotlineresync"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HubspotErrorCheck",
        ),
        migrations.DeleteModel(
            name="HubspotLineResync",
        ),
    ]
