# Generated by Django 3.2.21 on 2023-10-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maxmind", "0001_add_geoname_and_netblock_tables"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="netblock",
            index=models.Index(
                fields=["decimal_ip_start"], name="maxmind_net_decimal_dfdb1a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="netblock",
            index=models.Index(
                fields=["decimal_ip_end"], name="maxmind_net_decimal_6166c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="netblock",
            index=models.Index(
                fields=["decimal_ip_start", "decimal_ip_end"],
                name="maxmind_net_decimal_ab7249_idx",
            ),
        ),
    ]
