# Generated by Django 2.2.4 on 2019-09-04 20:11

from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0016_payment_type_choices"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("b2b_ecommerce", "0002_order_coupon_payment"),
    ]

    operations = [
        migrations.CreateModel(
            name="B2BCoupon",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("name", models.TextField()),
                ("coupon_code", models.CharField(max_length=50)),
                (
                    "discount_percent",
                    models.DecimalField(
                        decimal_places=5,
                        max_digits=20,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                (
                    "expiration_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="If set, the coupons will not be redeemable after this time",
                        null=True,
                    ),
                ),
                (
                    "activation_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="If set, the coupons will not be redeemable before this time",
                        null=True,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ecommerce.Company",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ecommerce.Product",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.AddField(
            model_name="b2border",
            name="discount",
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.CreateModel(
            name="B2BCouponAudit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "data_before",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, null=True
                    ),
                ),
                (
                    "data_after",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, null=True
                    ),
                ),
                (
                    "acting_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "coupon",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="b2b_ecommerce.B2BCoupon",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.AddField(
            model_name="b2border",
            name="coupon",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="b2b_ecommerce.B2BCoupon",
            ),
        ),
        migrations.CreateModel(
            name="B2BCouponRedemption",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="b2b_ecommerce.B2BCoupon",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="b2b_ecommerce.B2BOrder",
                    ),
                ),
            ],
            options={"unique_together": {("coupon", "order")}},
        ),
    ]
