# Generated by Django 2.2.4 on 2019-09-11 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("b2b_ecommerce", "0003_coupons")]

    operations = [
        migrations.AlterField(
            model_name="b2bcoupon",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="ecommerce.Company",
            ),
        )
    ]
