# Generated by Django 2.2.10 on 2020-04-06 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("b2b_ecommerce", "0005_b2border_contract_number")]

    operations = [
        migrations.AlterField(
            model_name="b2border",
            name="contract_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="b2border",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="b2b_ecommerce.B2BCoupon",
            ),
        ),
        migrations.AlterField(
            model_name="b2border",
            name="coupon_payment_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="ecommerce.CouponPaymentVersion",
            ),
        ),
        migrations.AlterField(
            model_name="b2border",
            name="discount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
    ]
