# Generated by Django 2.2.10 on 2020-07-20 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("b2b_ecommerce", "0006_b2border_admin_fix")]

    operations = [
        migrations.AddField(
            model_name="b2bcoupon",
            name="reusable",
            field=models.BooleanField(
                default=False,
                help_text="When checked, the coupon can be redeemed multiple times",
            ),
        ),
        migrations.AlterField(
            model_name="b2bcoupon",
            name="product",
            field=models.ForeignKey(
                blank=True,
                help_text="If no product is selected, the coupon is valid for any product",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="ecommerce.Product",
            ),
        ),
    ]
