# Generated by Django 3.2.15 on 2022-10-17 15:03

import django.db.models.deletion
from django.db import migrations, models


def backpopulate_b2b_lines(apps, schema_editor):
    """Create a B2BLine for each B2BOrder"""
    B2BOrder = apps.get_model("b2b_ecommerce", "B2BOrder")
    B2BLine = apps.get_model("b2b_ecommerce", "B2BLine")
    orders = B2BOrder.objects.iterator()
    for order in orders:
        B2BLine.objects.get_or_create(order=order)


class Migration(migrations.Migration):
    dependencies = [
        ("b2b_ecommerce", "0009_jsonField_from_django_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="B2BLine",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line",
                        to="b2b_ecommerce.b2border",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunPython(backpopulate_b2b_lines, migrations.RunPython.noop),
    ]
