# Generated by Django 3.2.23 on 2023-11-20 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0041_add_mit_tax_id_fields_20231120_2052"),
        ("b2b_ecommerce", "0010_b2bline"),
    ]

    operations = [
        migrations.AddField(
            model_name="b2border",
            name="customer_tax_identifier",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="b2border",
            name="customer_tax_identifier_name",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="b2border",
            name="mit_tax_identifier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="ecommerce.taxrate",
            ),
        ),
        migrations.AddField(
            model_name="b2border",
            name="tax_country_code",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="b2border",
            name="tax_rate",
            field=models.DecimalField(
                blank=True, decimal_places=4, default=0, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="b2border",
            name="tax_rate_name",
            field=models.CharField(default="VAT", max_length=100, null=True),
        ),
    ]
