# Generated by Django 4.2.9 on 2024-04-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("b2b_ecommerce", "0011_alter_b2bcoupon_coupon_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="b2bcoupon",
            name="coupon_code",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
