---
name: Add new issues to mitodl/hq

on:
  issues:
    types:
      - opened

jobs:
  add-to-hq:
    uses: mitodl/ol-github-workflows/.github/workflows/add-to-ol-hq.yaml@edd566dec1edd920d35ab1fb60b589cddc44afad # main
    secrets: inherit
