"""Constants for the courses app"""

DEFAULT_COURSE_IMG_PATH = "images/mit-dome.png"
CATALOG_COURSE_IMG_W_H = (335, 203)
CATALOG_COURSE_IMG_WAGTAIL_FILL = "fill-{}x{}".format(*CATALOG_COURSE_IMG_W_H)

COURSE_BG_IMG_W_H = (1900, 650)
COURSE_BG_IMG_WAGTAIL_FILL = "fill-{}x{}".format(*COURSE_BG_IMG_W_H)

COURSE_BG_IMG_MOBILE_W_H = (1024, 350)
COURSE_BG_IMG_MOBILE_WAGTAIL_FILL = "fill-{}x{}".format(*COURSE_BG_IMG_MOBILE_W_H)
